=== Caltech-IPAC/firefly/config/voservices/xml/tablemapper.dtd
<!-- DOCUMENT TYPE DEFINITION for IpacTable to VoTable mapper
     It allows to map a field of IPAC Table into differnt field of VOTable.
     It also allows to map several IPAC Table fields into an array field
     Version: 1.0
-->

<!ELEMENT TableMapper (VoServiceParam*, VoField+)>
<!ATTLIST TableMapper 
	  name CDATA #REQUIRED
	  desc CDATA #REQUIRED
	  serviceurl CDATA #REQUIRED
>

<-- Element defining FIELD metadata of VO table
    Must contain IpacField elements or have a default value set
    Most attributes come from VO Table standard
-->
<!ELEMENT VoField (IpacField*)>
<!ATTLIST VoField 
	  name CDATA #REQUIRED
	  coordsys CDATA (EQ_J2000 | EQ_B2000 | EC_J2000 | EC_B1950 | Galactic) #IMPLIED
	  desc CDATA #IMPLIED
	  unit CDATA #IMPLIED
	  ucd CDATA #IMPLIED
	  utype CDATA #IMPLIED
	  datatype (boolean | char | short | int | long | float | double) #IMPLIED
	  defaultvalue CDATA #IMPLIED
	  width CDATA #IMPLIED
	  optional (true|false) #IMPLIED
	  arraysize CDATA #IMPLIED
>

<!ELEMENT IpacField (EMPTY)>
<!ATTLIST IpacField
	  name CDATA #REQUIRED
	  format CDATA #IMPLIED
>

<!ELEMENT VoServiceParam (VoValues?)>
<!ATTLIST VoServiceParam
	name CDATA #REQUIRED
        coordsys CDATA (EQ_J2000 | EQ_B2000 | EC_J2000 | EC_B1950 | Galactic) #IMPLIED
	desc CDATA #IMPLIED 
        unit CDATA #IMPLIED
	datatype (boolean | char | short | int | long | float | double) #IMPLIED
        precision CDATA #IMPLIED
        ucd   CDATA #IMPLIED
	utype CDATA #IMPLIED
        value CDATA #IMPLIED
	testvalue CDATA #IMPLIED  
        arraysize CDATA #IMPLIED
>

<!-- VALUES expresses the values that can be taken by the data in a column. -->
<!ELEMENT VoValues (VoMin?, VoMax?, VoOption*)>

<!ELEMENT VoMin (EMPTY)>
<!ATTLIST VoMin
        value CDATA #REQUIRED
        inclusive (yes | no) "yes"
>
<!ELEMENT VoMax (EMPTY)>
<!ATTLIST VoMax
        value CDATA #REQUIRED
        inclusive (yes | no) "yes"
>
<!ELEMENT VoOption (EMPTY)>
<!ATTLIST VoOption
        name CDATA #IMPLIED
        value CDATA #REQUIRED
>

=== Caltech-IPAC/firefly/config/voservices/xml/finderchartToSiapMapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Project SYSTEM "./tablemapper.dtd">

<!--
    Finder Chart VO Service
    Implementation of Simple Image Access Specifications 1.0 2013-03-26
-->

<TableMapper name="FinderChartToSiap"
	     desc="Finder Chart v2 - Simple Image Search"
	     serviceurl="%finderchart.hostname%/applications/finderchart/servlet/FinderChartDataService">

<!-- required by the standard -->
<VoServiceParam name="POS"
		desc="The position of the region of interest, expressed as the right-ascension and declination of the field center, in decimal degrees using the ICRS coordinate system. A comma should delimit the two values; embedded whitespace is not permitted"
		unit="degrees"
		value="0,0"
		testvalue="163.6136,-11.784"
/>

<!-- required by the standard -->
<VoServiceParam name="SIZE"
		desc="The coordinate angular size of the region given in decimal degrees. The region may be specified using either one or two values. If only one value is given it applies to both coordinate axes."
		unit="degrees"
		value="0.0001"
		testvalue="0.5"
/>

<!-- required by the standard -->
<VoServiceParam name="FORMAT"
		desc="the desired format or formats of the images referenced by the output table. The value is a comma-delimited list where each element can be any recognized MIME-type"
		value="ALL"
		testvalue="image/fits">
  <VoValues>
    <VoOption value="METADATA"/>
    <VoOption value="ALL"/>
    <VoOption value="image/fits"/>
  </VoValues>
</VoServiceParam>

<!-- must be in the output -->
<VoField name="externalname"
	 ucd="VOX:Image_Title"
	 desc="Short description of the image (image external name)">
  <!-- Todo: combine GROUP + DESC -->
  <IpacField name="externalname"/>
</VoField>

<!-- must be in the output -->
<VoField name="wavelength"
	 ucd="INST_ID"
	 desc="The instrument and detector used to make the observation">
  <IpacField name="wavelength"/>
</VoField>


<!-- must be in the output -->
<VoField name="ra"
	 ucd="POS_EQ_RA_MAIN"
	 unit="degree"
	 datatype="double"
	 desc="The ICRS right-ascension of the center of the image">
  <IpacField name="ra"/>
</VoField>

<!-- must be in the output -->
<VoField name="dec"
	 ucd="POS_EQ_DEC_MAIN"
	 unit="degree"
	 datatype="double"
	 desc="The ICRS declination of the center of the image">
  <IpacField name="dec"/>
</VoField>

<!-- must be in the output -->
<VoField name="naxes"
	 ucd="VOX:Image_Naxes"
	 datatype="int"
	 defaultvalue="2"
	 desc="The number of image axes"/>

<!-- must be in the output -->
<VoField name="naxis"
	 ucd="VOX:Image_Naxis"
	 datatype="int"
	 arraysize="*"
	 desc="The array value giving the length in pixels of each image axis">
  <IpacField name="naxis1"/>
  <IpacField name="naxis2"/>
</VoField>

<!-- must be in the output>
<VoField name="cdelt"
	 ucd="VOX:Image_Scale"
	 unit="degrees/pixel"
	 datatype="double"
	 arraysize="*"
	 desc="The array value giving the scale in degrees per pixel of each image axis">
  <IpacField name="cdelt1" format="%1.1E"/>
  <IpacField name="cdelt2" format="%1.1E"/>
</VoField-->

<!-- must be in the output -->
<VoField name="dataFormat"
	 ucd="VOX:Image_Format"
	 desc="MIME-type of the object associated with the image access reference">
  <IpacField name="dataFormat"/>
</VoField>

<!-- must be in the output -->
<VoField name="imageAccessUrl"
         ucd="VOX:Image_AccessReference"
	 desc="The URL to be used to access or retrieve the image">
  <IpacField name="accessUrl"/>
</VoField>

<!-- custom field -->
<VoField name="imageAnc1AccessUrl"
         desc="The URL to retrieve the image and important ancillary products (mask, uncertainty, etc.) as a zip archive"
	 optional="true">
  <IpacField name="accessWithAnc1Url"/>
</VoField>

<!-- should be in the output>
<VoField name="mjDateObs"
	 ucd="VOX:Image_MJDateObs"
	 datatype="double"
	 unit="days"
	 desc="Modified Julian date of the observation">
  <IpacField name="mjDateObs"/>
</VoField-->

</TableMapper>
