=== Caltech-IPAC/firefly/config/hydra/project.dtd
<!-- This document defines the element and attributes for creating a project within the Hydra Configurable Interface.
@title project.dtd
@root Project
-->

<!-- Hydra projects are created using a single XML configuration file and various Java server-side search processors that
assist in the catalog and image search and retrieval.  The configuration file defines the entire layout and behavior of
the search and results forms, as well as defines the parameters required for all query processing and event behavior.

The XML configuration file is designed to dynamically configure any project.  When redeployed, changes made to the
configuration file will produce immediate changes in the Hydra application (after a browser refresh).

'Project' is the root element containing all of the properties and attributes for a Hydra project.  To get started,
the minimum XML needed (to see a new project show up in Hydra) is:
<blockquote>
<img src="../hydra_images/helloWorld.jpg"/>
%
<Project>
    <Name>hWorld</Name>
    <Title>Hello World!</Title>
    <SearchType>
        <Name>search_1</Name>
        <Title>Test Search</Title>
        <Form>
            <FieldGroup>
                <Label>Hello World!</Label>
            </FieldGroup>
        </Form>
        <Result>
            <Layout>
                <SplitPanel/>
            </Layout>
        </Result>
    </SearchType>
</Project>
%
</blockquote>

When adding a new project to Hydra, be sure to also add the project to projectList.xml
(<a href="projectList.dtd.html">projectList.dtd</a>):
<blockquote>
%
<ProjectList>
    ...
    <ProjectItem id="hWorld" active="true">
        <Display>Hello World!</Display>
        <Tooltip>Hello World Test</Tooltip>
        <ConfigFile>test/hWorld.xml</ConfigFile>
    </ProjectItem>
</ProjectList>
%
</blockquote> 
 -->
<!ELEMENT  Project (Name, Title, Properties?, OverrideProperties?, Catalog*, SearchGroup*)>

<!-- Defines grouping among the SearchType -->
<!ELEMENT  SearchGroup (Name, Title, SearchType*)>

<!-- Defines optional Catalog entries to be prepended to list of regular catalogs for Catalog Search dialog -->
<!ELEMENT  Catalog (Host, Credentials?, CatalogURL, OriginalFilename, MasterCatFilename, AddtlReqSearchParams?)>
<!--
     @attr name The name of the catalog that will be prepended to the public list.  Ex: WISEPASS1
-->
<!ATTLIST    Catalog name CDATA #IMPLIED>

<!ELEMENT  Host (#PCDATA)>

<!ELEMENT  Credentials EMPTY>
<!ATTLIST    Credentials login CDATA #IMPLIED>
<!ATTLIST    Credentials password CDATA #IMPLIED>

<!ELEMENT  CatalogURL (#PCDATA)>

<!ELEMENT  OriginalFilename (#PCDATA)>

<!ELEMENT  MasterCatFilename (#PCDATA)>

<!ELEMENT  AddtlReqSearchParams (GatorParam*)>

<!ELEMENT  GatorParam EMPTY>
<!ATTLIST    GatorParam requestName CDATA #IMPLIED>
<!ATTLIST    GatorParam masterCatName CDATA #IMPLIED>


<!-- Defines the search type properties and attributes. -->
<!ELEMENT  SearchType (Name, Title, Tooltip?, Access?, (CommandId|(Form, Query*, Result?)))>
<!-- An identifier that maps to the help text defined in the index.html file. -->
<!ATTLIST    SearchType helpId CDATA #IMPLIED>
<!ATTLIST    SearchType layoutSelector (true|false) "false">

<!ELEMENT  CommandId (#PCDATA)>

<!ELEMENT  Properties (Param*)>

<!ELEMENT  OverrideProperties (Param*)>

<!ELEMENT  Access EMPTY>
<!-- A comma delimited string of roles. The included roles will allow access to the content. -->
<!ATTLIST    Access includes CDATA #IMPLIED>
<!-- A comma delimited string of roles. The included roles will exclude access to the content. -->
<!ATTLIST    Access excludes CDATA #IMPLIED>

<!--
A searchtype form consists of at least one top level FieldGroup container, and may optionally define
FormEventWorkers that add custom behavior to the form.
-->
<!ELEMENT  Form (FormEventWorker*, FieldGroup+)>
<!ATTLIST    Form title CDATA #IMPLIED>
<!ATTLIST    Form minSize CDATA #IMPLIED>
<!ATTLIST    Form helpId CDATA #IMPLIED>

<!ELEMENT  Query (Constraints?, Param*, Metadata?, Download?)>
<!ATTLIST    Query xid CDATA #IMPLIED>
<!ATTLIST    Query ref-xid CDATA #IMPLIED>
<!ATTLIST    Query id CDATA #REQUIRED>
<!-- A string that identifies which search processor to use. Possible search processors are: "SearchBCD", "WiseQuery", "WiseQueryArtifact", "WIseFileRetrieve", "PlanckImagesQuery", "GatorQuery", "2MassQuery", "2MassQueryArtifact" and "2MassFileRetrieve", -->
<!ATTLIST    Query searchProcessorId CDATA #IMPLIED>

<!ELEMENT  Constraints (Condition|And|Or)>
<!ELEMENT  And (Condition+, Or?)>
<!ELEMENT  Or (Condition+, And?)>
<!ELEMENT  Condition EMPTY>
<!ATTLIST    Condition fieldDefVisible CDATA #IMPLIED>
<!ATTLIST    Condition fieldDefHidden CDATA #IMPLIED>
<!ATTLIST    Condition fieldDefId CDATA #IMPLIED>
<!ATTLIST    Condition value CDATA #IMPLIED>

<!-- This popup panel provides an interface for downloading catalog and image files. -->
<!ELEMENT  Download (Param*, SearchFormParam*, Form?)>
<!ATTLIST    Download id CDATA #REQUIRED>
<!ATTLIST    Download title CDATA #IMPLIED>
<!ATTLIST    Download filePrefix CDATA #IMPLIED>
<!ATTLIST    Download titlePrefix CDATA #IMPLIED>
<!ATTLIST    Download maxRows CDATA #IMPLIED>

<!-- This panel provides search results data. The data can be shown in table or text form. -->
<!ELEMENT  Result (EventWorker*, Layout)>
<!ATTLIST    Result xid CDATA #IMPLIED>
<!ATTLIST    Result ref-xid CDATA #IMPLIED>

<!-- This panel provides ... -->
<!ELEMENT  FieldGroup (Title?, Tooltip?, Access?, (FieldGroup|PreDefField|Label|HIDDEN|String|Date|DEGREE|Double|Float|EMail|EnumString|Integer|Password|Pattern|Lat|Lon|MultiCoord|File|Help)*)>
<!ATTLIST    FieldGroup xid CDATA #IMPLIED>
<!ATTLIST    FieldGroup ref-xid CDATA #IMPLIED>
<!-- A string defining the FieldGroup's panel type. -->
<!ATTLIST    FieldGroup type (default|tabPane|activeTabPane|collapsiblePanel|activeCollapsiblePanel|datePanel|frame) "default">
<!ATTLIST    FieldGroup typeName CDATA #IMPLIED>
<!ATTLIST    FieldGroup labelWidth CDATA "100">
<!ATTLIST    FieldGroup direction (vertical|horizontal) "vertical">
<!ATTLIST    FieldGroup width CDATA #IMPLIED>
<!ATTLIST    FieldGroup height CDATA #IMPLIED>
<!ATTLIST    FieldGroup spacing CDATA "0">
<!ATTLIST    FieldGroup align (left|center|right) "right">
<!ATTLIST    FieldGroup downloadRestriction CDATA #IMPLIED>

<!-- This element defines the pre-defined fields for inputing parameters. -->
<!ELEMENT  PreDefField (Param*)>
<!-- A string that identitfies one of the available pre-defined inputs. Possible preDefField values are: "targetPanel", "RangePanel", "catalogPopupPanel", ... -->
<!ATTLIST    PreDefField id CDATA #REQUIRED>

<!ELEMENT  HIDDEN (ID?, Name, Default)>
<!ELEMENT  String (ID?, Name, Title, PreferWidth?, Icon?, Default?, Pref-Key?, Mask?, MaxWidth?, Cached?, NullAllowed?, LongDescription?, ShortDescription?, ErrorDescription?)>
<!ELEMENT  Date (ID?, Name, Title, Icon?, Default?, Pref-Key?, Mask?, PreferWidth?, MaxWidth?, Min?, Max?, Cached?, Format*, NullAllowed?, LongDescription?, ShortDescription?, ErrorDescription?)>
<!ATTLIST    Date minBoundType (exclusive|inclusive|undefined) "undefined">
<!ATTLIST    Date maxBoundType (exclusive|inclusive|undefined) "undefined">
<!ELEMENT  DEGREE (ID?, Name, Title, Default?, PreferWidth?, LongDescription?, ShortDescription?, ErrorDescription?, Icon?, Mask?, PreferWidth?, MaxWidth?, Min?, Max?, Cached?, NullAllowed?)>
<!ATTLIST    DEGREE units (degree|arcmin|arcsec) "degree">
<!ELEMENT  Double (ID?, Name, Title, LongDescription?, ShortDescription?, Icon?, Default?, Pref-Key?, ErrorDescription?, Mask?, MaxWidth?, Min?, Max?, Precision?, Cached?, NullAllowed?)>
<!ATTLIST    Double scientificAllowed (true|false) "false">
<!ATTLIST    Double minBoundType (exclusive|inclusive|undefined) "undefined">
<!ATTLIST    Double maxBoundType (exclusive|inclusive|undefined) "undefined">
<!ELEMENT  Float (ID?, Name, Title, LongDescription?, ShortDescription?, Icon?, Default?, Pref-Key?, ErrorDescription?, Mask?, PreferWidth?, MaxWidth?, Min?, Max?, Precision?, Cached?, NullAllowed?)>
<!ATTLIST    Float scientificAllowed (true|false) "false">
<!ATTLIST    Float minBoundType (exclusive|inclusive|undefined) "undefined">
<!ATTLIST    Float maxBoundType (exclusive|inclusive|undefined) "undefined">
<!ELEMENT  EMail (ID?, Name, Title, LongDescription?, ShortDescription?, Icon?, Default?, Pref-Key?, ErrorDescription?, Mask?, PreferWidth?, MaxWidth?, Cached?, NullAllowed?)>
<!ELEMENT  EnumString (ID?, Name, Title, PreferWidth?, Mask?, Default?, MaxWidth?, Icon?,Pref-Key?, Cached?, NullAllowed?, LongDescription?, ShortDescription?, ErrorDescription?, EnumValue+)>
<!ATTLIST    EnumString orientation (horizontal|vertical) "horizontal">
<!ELEMENT  Integer (ID?, Name, Title, LongDescription?, ShortDescription?, Icon?, Default?, Pref-Key?, ErrorDescription?, Mask?, PreferWidth?, MaxWidth?, Cached?, NullAllowed?)>
<!ELEMENT  Lat (ID?, Name, Title, LongDescription?, ShortDescription?, Icon?, Default?, ErrorDescription?, Mask?, PreferWidth?, MaxWidth?, Cached?, NullAllowed?)>
<!ELEMENT  Lon (ID?, Name, Title, LongDescription?, ShortDescription?, Icon?, Default?, ErrorDescription?, Mask?, PreferWidth?, MaxWidth?, Cached?, NullAllowed?)>
<!ELEMENT  MultiCoord (ID?, Name, Title, LongDescription?, ShortDescription?, Icon?, Default?, ErrorDescription?, Mask?, PreferWidth?, MaxWidth?, Cached?, NullAllowed?)>
<!ELEMENT  Password (ID?, Name, Title, LongDescription?, ShortDescription?, Icon?, Default?, ErrorDescription?, Mask?, PreferWidth?, MaxWidth?, Cached?, NullAllowed?)>
<!ELEMENT  Pattern (ID?, Name, Title, PreferWidth?, Icon?, Default?, Pref-Key?, Mask?, ValidateMask?, MaxWidth?, Cached?, NullAllowed?, LongDescription?, ShortDescription?, ErrorDescription?)>
<!ELEMENT  File (ID?, Name, Title, Icon?, Default?, Mask?, PreferWidth?, MaxWidth?, Cached?, Size?, LongDescription?, ShortDescription?, ErrorDescription?)>
<!ELEMENT  Help (Title)>
<!ATTLIST    Help helpId CDATA #REQUIRED>
<!ELEMENT  EnumValue (Title, ShortDescription?, IntValue?)>
<!ATTLIST    EnumValue id CDATA #REQUIRED>

<!-- Defines the layout of the panel -->
<!ELEMENT  Layout (SplitPanel)>

<!-- Defines the position and orientation of the split panel. -->
<!ELEMENT  SplitPanel ((North|West|East|South)*, Center)>
<!ATTLIST    SplitPanel xid CDATA #IMPLIED>
<!ATTLIST    SplitPanel ref-xid CDATA #IMPLIED>

<!-- Defines the results panel position and type. North will postion the panel along the top of the display. -->
<!ELEMENT  North ((Table|Preview|Form|SplitPanel|HtmlLoader)*)>
<!ATTLIST    North layout (horizontal|vertical|tab|fixedTab) "horizontal">
<!ATTLIST    North title CDATA #IMPLIED>
<!ATTLIST    North initialHeight CDATA #IMPLIED>
<!ATTLIST    North groupId CDATA #IMPLIED>
<!ATTLIST    North helpId CDATA #IMPLIED>
<!ATTLIST    North tagIt (true|false) "false">

<!-- Defines the results panel position and type. West will postion the panel along the left side of the display. -->
<!ELEMENT  West ((Table|Preview|Form|SplitPanel|HtmlLoader)*)>
<!ATTLIST    West layout (horizontal|vertical|tab|fixedTab) "horizontal">
<!ATTLIST    West title CDATA #IMPLIED>
<!ATTLIST    West initialWidth CDATA #IMPLIED>
<!ATTLIST    West groupId CDATA #IMPLIED>
<!ATTLIST    West helpId CDATA #IMPLIED>
<!ATTLIST    West tagIt (true|false) "false">

<!-- Defines the results panel position and type. -->
<!ELEMENT  Center (Table|Preview|Form|SplitPanel|HtmlLoader)+>
<!ATTLIST    Center layout (horizontal|vertical|tab|fixedTab) "horizontal">
<!ATTLIST    Center layoutName CDATA #IMPLIED>
<!ATTLIST    Center title CDATA #IMPLIED>
<!ATTLIST    Center groupId CDATA #IMPLIED>
<!ATTLIST    Center helpId CDATA #IMPLIED>
<!ATTLIST    Center tagIt (true|false) "false">

<!-- Defines the results panel position and type. East will postion the panel along the right side of the display. -->
<!ELEMENT  East ((Table|Preview|Form|SplitPanel|HtmlLoader)*)>
<!ATTLIST    East layout (horizontal|vertical|tab|fixedTab) "horizontal">
<!ATTLIST    East title CDATA #IMPLIED>
<!ATTLIST    East initialWidth CDATA #IMPLIED>
<!ATTLIST    East groupId CDATA #IMPLIED>
<!ATTLIST    East helpId CDATA #IMPLIED>
<!ATTLIST    East tagIt (true|false) "false">

<!-- Defines the results panel position and type. South will postion the panel along the bottom of the display. -->
<!ELEMENT  South ((Table|Preview|Form|SplitPanel|HtmlLoader)*)>
<!ATTLIST    South layout (horizontal|vertical|tab|fixedTab) "horizontal">
<!ATTLIST    South title CDATA #IMPLIED>
<!ATTLIST    South initialHeight CDATA #IMPLIED>
<!ATTLIST    South groupId CDATA #IMPLIED>
<!ATTLIST    South helpId CDATA #IMPLIED>
<!ATTLIST    South tagIt (true|false) "false">

<!--Available Params:
    show-filter (true|false)
    show-options (true|false)
    show-popout (true|false)
    show-title (true|false)
    show-toolbar (true|false)
    show-paging (true|false)
    show-save (true|false)
-->
<!ELEMENT  Table (QueryId, Name?, Title?, ShortDescription?, Width?, Height?, TopIndent?, BottomIndent?, LeftIndent?, RightIndent?, Param*, View*)>
<!ATTLIST    Table xid CDATA #IMPLIED>
<!ATTLIST    Table ref-xid CDATA #IMPLIED>
<!ATTLIST    Table id CDATA #IMPLIED>
<!ATTLIST    Table align (center|left|right) "left">
<!ATTLIST    Table type CDATA #REQUIRED>

<!ELEMENT  View (QueryId?, Name, ShortDescription?, Index?, Param*)>
<!ATTLIST    View id CDATA #IMPLIED>
<!ATTLIST    View type (ImageGridView|XYTableView) "ImageGridView">

<!ELEMENT  Preview (Constraints?, QueryId*, EventWorkerId*, Title?, ShortDescription?, Width?, Height?, TopIndent?, BottomIndent?, LeftIndent?, RightIndent?, Param*)>
<!ATTLIST    Preview xid CDATA #IMPLIED>
<!ATTLIST    Preview ref-xid CDATA #IMPLIED>
<!ATTLIST    Preview id CDATA #IMPLIED>
<!ATTLIST    Preview align (center|left|right) "left">
<!ATTLIST    Preview frameType (titleFrame|frameOnly|noFrame) "frameOnly">
<!ATTLIST    Preview type CDATA #REQUIRED>

<!--
FormEventWorkers add custom behavior to the form outside of the normal behavior provided by Firefly.  Custom behavior may include
hiding or showing certain fields based on values of other fields, or resizing tab panes, etc.  Each FormEventWorker requires a
different set of Param key/value configuration settings for proper functionality.  See below.

FieldDefVisibilityControl parameters:
  masters:
  show:
  hide:
  retainSpace:

CollapsiblePanelVisibilityControl parameters:
  masters:
  slaves:

TabPaneSizeControl parameters:
  tabPaneName:
  <tab name>:
-->
<!ELEMENT  FormEventWorker (ShortDescription?, Param*, FieldDefIds?)>
<!--
  @attr id (required) The ID associated with this FormEventWorker
  @attr type (required) The type of FormEventWorker.  Firefly contains the following FormEventWorkers: FieldDefVisibilityControl, CollapsiblePanelVisibilityControl,
             TabPaneSizeControl, FieldChangeControl.  WISE additionally has the following custom FormEventWorkers: WisePreviewControl
  @attr xid (optional) XML object storage ID.  Used internally to save XML objects for subsequent referencing
  @attr ref-xid (optional) XML object retrieval ID.  Used internally to reference previously-stored XML objects
-->
<!ATTLIST FormEventWorker
    id CDATA #REQUIRED
    type CDATA #REQUIRED
    xid CDATA #IMPLIED
    ref-xid CDATA #IMPLIED
>

<!ELEMENT  HtmlLoader (QueryId, Label?, Param*)>

<!ELEMENT  EventWorker (QueryId*, ShortDescription?, Param*)>
<!ATTLIST    EventWorker xid CDATA #IMPLIED>
<!ATTLIST    EventWorker ref-xid CDATA #IMPLIED>
<!ATTLIST    EventWorker id CDATA #REQUIRED>
<!ATTLIST    EventWorker type CDATA #REQUIRED>

<!ELEMENT  Metadata (Param*)>

<!ELEMENT  FieldDefIds (Param*)>

<!ELEMENT  QueryId (#PCDATA)>

<!ELEMENT  EventWorkerId (#PCDATA)>

<!-- Used for passing key-value pair data to the server. -->
<!ELEMENT  Param EMPTY>
<!-- A key mapping to a single value, duplicate keys are not allowed. -->
<!ATTLIST    Param key CDATA #REQUIRED>
<!ATTLIST    Param value CDATA #REQUIRED>

<!ELEMENT  SearchFormParam EMPTY>
<!ATTLIST    SearchFormParam keyName CDATA #REQUIRED>
<!ATTLIST    SearchFormParam keyValue CDATA #REQUIRED>
<!ATTLIST    SearchFormParam createParams CDATA #REQUIRED>

<!ELEMENT  Cached EMPTY>
<!ELEMENT  NullAllowed EMPTY>

<!ELEMENT  Label (#PCDATA)>
<!ELEMENT  ID (#PCDATA)>
<!ELEMENT  Name (#PCDATA)>
<!ELEMENT  Title (#PCDATA)>
<!ATTLIST  Title  width CDATA #IMPLIED>
<!ELEMENT  Tooltip (#PCDATA)>
<!ELEMENT  LongDescription (#PCDATA)>
<!ELEMENT  ShortDescription (#PCDATA)>
<!ELEMENT  Icon (#PCDATA)>
<!ELEMENT  Default (#PCDATA)>
<!ELEMENT  Pref-Key (#PCDATA)>
<!ELEMENT  ErrorDescription (#PCDATA)>
<!ELEMENT  Mask (#PCDATA)>
<!ELEMENT  ValidateMask (#PCDATA)>
<!ELEMENT  PreferWidth (#PCDATA)>
<!ELEMENT  Size (#PCDATA)>
<!ELEMENT  MaxWidth (#PCDATA)>
<!ELEMENT  Value (#PCDATA)>
<!ELEMENT  IntValue (#PCDATA)>
<!ELEMENT  Index (#PCDATA)>

<!ELEMENT  Format (#PCDATA)>
<!ELEMENT  Min (#PCDATA)>
<!ELEMENT  Max (#PCDATA)>
<!ELEMENT  Precision (#PCDATA)>

<!-- Defines the width of the pane. -->
<!ELEMENT  Width (#PCDATA)>
<!-- Defines the height of the pane. -->
<!ELEMENT  Height (#PCDATA)>
<!ELEMENT  TopIndent (#PCDATA)>
<!ELEMENT  BottomIndent (#PCDATA)>
<!ELEMENT  LeftIndent (#PCDATA)>
<!ELEMENT  RightIndent (#PCDATA)>


<!ELEMENT xi:include EMPTY>
<!ATTLIST xi:include
    xmlns:xi   CDATA       #FIXED    "http://www.w3.org/2001/XInclude"
    href       CDATA       #REQUIRED
    parse      (xml|text)  "xml"
>

=== Caltech-IPAC/firefly/config/hydra/configurable/planck/res_planck_catalog2.xml
<!DOCTYPE Result SYSTEM "../../project.dtd">
<!-- Result linked with searches in "planck.xml":                               -->
<!--    Planck Data Release II: Single Frequency Catalog(All-Sky)               -->
<!--    PCCS Catalog Search (Jan., 2013): Single Frequency (All-Sky)           -->
<!--    PCCS Catalog Search (Jan., 2013): Multiple Frequency (Name/Position)   -->
<Result xid="planckResult">
    <EventWorker id="imagesWorker" type="DataSetQuery" xid="imagesWorker">
        <QueryId>
            planck30r2,planck44r2,planck70r2,planck100r2,planck143r2,planck217r2,planck353r2,planck545r2,planck857r2
        </QueryId>
        <Param key="searchProcessorId" value="planckImagesQuery2"/>
        <Param key="Events" value="onRowHighlightChange,TablePreviewEventHub.TableShow,TabPane.tabSelected"/>
    </EventWorker>
    <Layout>
        <SplitPanel>
            <!-- Image Grid Preview -->
            <South layout="horizontal" initialHeight="300">
                <Preview type="BasicPreviewImageGrid">
                    <QueryId>
                        planck30r2,planck44r2,planck70r2,planck100r2,planck143r2,planck217r2,planck353r2,planck545r2,planck857r2
                    </QueryId>
                    <EventWorkerId>imagesWorker</EventWorkerId>
                    <Title>Images Grid</Title>
                    <Param key="Readout"
                           value="0=TITLE,4=EQ_J2000,2=EQ_J2000_DEG,3=IMAGE_PIXEL,1=GALACTIC,5=EQ_B1950"/>
                    <Param key="LockRelated" value="true"/>
                    <Param key="UseScrollBars" value="false"/>
                    <Param key="TitleDesc.PLANCK"
                           value="( 2.0 degree on a side with Galactic north up, east left. 30/44/70 are 60x60 2-arcmin pixels, 100-857 are 120x120 1-arcmin pixels )"/>
                    <Param key="TitleDesc.WMAP"
                           value="(2.0 degree on a side with Galactic north up, east left. 60x60 2-arcmin pixels)"/>
                    <Param key="TitleDesc.IRAS"
                           value="(2.0 degree on a side with Galactic north up, east left. 120x120 1-arcmin pixels)"/>
                </Preview>
            </South>
            <!-- Details panel on left -->
            <East layout="fixedTab" initialWidth="400">
                <Preview type="RowDetails">
                    <Title>Details</Title>
                    <Param key="NOTES_PROC_ID" value="planckNotesQuery"/>
                </Preview>
            </East>
            <!-- Catalog tables -->
            <Center layout="tab" tagIt='true' helpId="results">
                <Table type="TABLE">
                    <QueryId>planck30r2</QueryId>
                    <Title>30 GHz</Title>
                    <ShortDescription>30 GHz catalog entry</ShortDescription>
                </Table>
                <Table type="TABLE">
                    <QueryId>planck44r2</QueryId>
                    <Title>44 GHz</Title>
                    <ShortDescription>44 GHz catalog entry</ShortDescription>
                </Table>
                <Table type="TABLE">
                    <QueryId>planck70r2</QueryId>
                    <Title>70 GHz</Title>
                    <ShortDescription>70 GHz catalog entry</ShortDescription>
                </Table>
                <Table type="TABLE">
                    <QueryId>planck100r2</QueryId>
                    <Title>100 GHz</Title>
                    <ShortDescription>100 GHz catalog entry</ShortDescription>
                </Table>
                <Table type="TABLE">
                    <QueryId>planck143r2</QueryId>
                    <Title>143 GHz</Title>
                    <ShortDescription>143 GHz catalog entry</ShortDescription>
                </Table>
                <Table type="TABLE">
                    <QueryId>planck217r2</QueryId>
                    <Title>217 GHz</Title>
                    <ShortDescription>217 GHz catalog entry</ShortDescription>
                </Table>
                <Table type="TABLE">
                    <QueryId>planck353r2</QueryId>
                    <Title>353 GHz</Title>
                    <ShortDescription>353 GHz catalog entry</ShortDescription>
                </Table>
                <Table type="TABLE">
                    <QueryId>planck545r2</QueryId>
                    <Title>545 GHz</Title>
                    <ShortDescription>545 GHz catalog entry</ShortDescription>
                </Table>
                <Table type="TABLE">
                    <QueryId>planck857r2</QueryId>
                    <Title>857 GHz</Title>
                    <ShortDescription>857 GHz catalog entry</ShortDescription>
                </Table>
                <Table type="TABLE">
                    <QueryId>planckszmmf1</QueryId>
                    <Title>SZ MMF1</Title>
                    <ShortDescription>SZ MMF1</ShortDescription>
                </Table>
                <Table type="TABLE">
                    <QueryId>planckszmmf3</QueryId>
                    <Title>SZ MMF3</Title>
                    <ShortDescription>SZ MMF3</ShortDescription>
                </Table>
                <Table type="TABLE">
                    <QueryId>planckszpws</QueryId>
                    <Title>SZ PwS</Title>
                    <ShortDescription>SZ PWS</ShortDescription>
                </Table>
                <Table type="TABLE">
                    <QueryId>planckszunion</QueryId>
                    <Title>SZ UNION</Title>
                    <ShortDescription>SZ UNION</ShortDescription>
                </Table>
            </Center>
        </SplitPanel>
    </Layout>
</Result>

=== Caltech-IPAC/firefly/config/hydra/configurable/wise/pv_band2_mos.xml
<!DOCTYPE Preview SYSTEM "../../project.dtd" [
        <!ENTITY prm_pv_common_params  SYSTEM "prm_pv_common_params.xml.txt">
        ]>

<Preview type="DATA_VIEW" id="prev_band_2">
    <Constraints>
        <Condition fieldDefId="band" value="2"/>
    </Constraints>

    <QueryId>wiseMOSQuery_1b</QueryId>
    <EventWorkerId>targetMOS</EventWorkerId>
    <EventWorkerId>diff_spikes_2,halos_2,ghosts_2,latents_2</EventWorkerId>
    <Title>Preview 2</Title>

    &prm_pv_common_params;
    <Param key="ExtraParams" value="band=2"/>
    <Param key="Title" value="WISE Band 2"/>

    <!-- override params-->
    <Param key="ArgCols" value="scan_id,frame_num,ra_obj,dec_obj,image_set"/>
    <Param key="Stretch" value="zscale=true,Type=Linear"/>
    <Param key="ColorPreferenceKey" value="UseMetaTag:ProductLevel:1b=WISE-Band2-L1,Default=WISE-Band2-L3"/>
</Preview>

=== Caltech-IPAC/firefly/config/hydra/configurable/wise/fg_3band_sel.xml
<!DOCTYPE FieldGroup SYSTEM "../../project.dtd">

<FieldGroup xid="bandSelection" labelWidth="140">
    <EnumString>
        <ID>band_3</ID>
        <Name>band</Name>
        <Title>Return the following bands:</Title>
        <Mask>[CHECKBOX]</Mask>
        <Default>_all_</Default>
        <ShortDescription>Band Selection: W1=3.4μm, W2=4.6μm, W3=12μm</ShortDescription>
        <ErrorDescription>Please select at least one band.</ErrorDescription>
        <EnumValue id="1">
            <Title>W1</Title>
        </EnumValue>
        <EnumValue id="2">
            <Title>W2</Title>
        </EnumValue>
        <EnumValue id="3">
            <Title>W3</Title>
        </EnumValue>
    </EnumString>
</FieldGroup>

=== Caltech-IPAC/firefly/config/hydra/configurable/wise/f_size.xml
<!DOCTYPE DEGREE SYSTEM "../../project.dtd">

<DEGREE units="arcsec">
    <Name>size</Name>
    <Title>Search Region (Square) Size</Title>
    <Default>30</Default>
    <PreferWidth>16</PreferWidth>
    <ShortDescription>Enter the region size of the search</ShortDescription>
    <ErrorDescription>Region size out of range</ErrorDescription>
    <Min>1</Min>
    <Max>43200</Max>
    <Cached/>
</DEGREE>

=== Caltech-IPAC/firefly/config/hydra/configurable/planck/res_planck_image.xml
<!DOCTYPE Result SYSTEM "../../project.dtd">


<Result xid="planckimagResult">
    <EventWorker id="imagesWorker2" type="DataSetQuery" xid="imagesWorker2">
        <QueryId>
            planck30,planck44,planck70,planck100,planck143,planck217,planck353,planck545,planck857
        </QueryId>
        <Param key="searchProcessorId" value="planckCutoutQuery"/>
        <Param key="Events" value="SearchResultEnd"/>
    </EventWorker>
    <Layout>
        <SplitPanel>
            <South layout="fixedTab" initialHeight="350">

                <Preview type="BasicPreviewImageGrid">
                    <QueryId>
                        planck30,planck44,planck70,planck100,planck143,planck217,planck353,planck545,planck857
                    </QueryId>
                    <EventWorkerId>imagesWorker2</EventWorkerId>
                    <Title>Cutouts</Title>
                    <Param key="Readout"
                           value="0=TITLE,2=IMAGE_PIXEL,1=GALACTIC,3=Pixel Size"/>
                    <Param key="LockRelated" value="true"/>
                    <Param key="UseScrollBars" value="false"/>
                    <Param key="TitleDesc.PLANCK"
                           value="(Planck Cutouts)"/>
                    <Param key="TitleDesc.WMAP"
                           value="(WMAP Cutouts)"/>
                    <Param key="TitleDesc.IRAS"
                           value="(IRAS Cutouts from ISSA plates)"/>
                </Preview>
            </South>
            <East layout="fixedTab" initialWidth="200">
                <Preview type="RowDetails">
                    <Title>Notes/Details</Title>
                    <Param key="NOTES_PROC_ID" value="planckNotesQuery"/>
                </Preview>
            </East>
            <Center layout="tab" tagIt='true' helpId="results">
                <Table type="TABLE">
                    <QueryId>planck30</QueryId>
                    <Title>30 GHz</Title>
                    <ShortDescription>30 GHz</ShortDescription>
                </Table>
                <Table type="TABLE">
                    <QueryId>planck44</QueryId>
                    <Title>44 GHz</Title>
                    <ShortDescription>44 GHz</ShortDescription>
                </Table>
                <Table type="TABLE">
                    <QueryId>planck70</QueryId>
                    <Title>70 GHz</Title>
                    <ShortDescription>70 GHz</ShortDescription>
                </Table>
                <Table type="TABLE">
                    <QueryId>planck100</QueryId>
                    <Title>100 GHz</Title>
                    <ShortDescription>100 GHz</ShortDescription>
                </Table>
                <Table type="TABLE">
                    <QueryId>planck143</QueryId>
                    <Title>143 GHz</Title>
                    <ShortDescription>143 GHz</ShortDescription>
                </Table>
                <Table type="TABLE">
                    <QueryId>planck217</QueryId>
                    <Title>217 GHz</Title>
                    <ShortDescription>217 GHz</ShortDescription>
                </Table>
                <Table type="TABLE">
                    <QueryId>planck353</QueryId>
                    <Title>353 GHz</Title>
                    <ShortDescription>353 GHz</ShortDescription>
                </Table>
                <Table type="TABLE">
                    <QueryId>planck545</QueryId>
                    <Title>545 GHz</Title>
                    <ShortDescription>545 GHz</ShortDescription>
                </Table>
                <Table type="TABLE">
                    <QueryId>planck857</QueryId>
                    <Title>857 GHz</Title>
                    <ShortDescription>857 GHz</ShortDescription>
                </Table>
            </Center>
        </SplitPanel>
    </Layout>
</Result>
