=== Caltech-IPAC/firefly/config/hydra/project.dtd
<!-- This document defines the element and attributes for creating a project within the Hydra Configurable Interface.
@title project.dtd
@root Project
-->

<!-- Hydra projects are created using a single XML configuration file and various Java server-side search processors that
assist in the catalog and image search and retrieval.  The configuration file defines the entire layout and behavior of
the search and results forms, as well as defines the parameters required for all query processing and event behavior.

The XML configuration file is designed to dynamically configure any project.  When redeployed, changes made to the
configuration file will produce immediate changes in the Hydra application (after a browser refresh).

'Project' is the root element containing all of the properties and attributes for a Hydra project.  To get started,
the minimum XML needed (to see a new project show up in Hydra) is:
<blockquote>
<img src="../hydra_images/helloWorld.jpg"/>
%
<Project>
    <Name>hWorld</Name>
    <Title>Hello World!</Title>
    <SearchType>
        <Name>search_1</Name>
        <Title>Test Search</Title>
        <Form>
            <FieldGroup>
                <Label>Hello World!</Label>
            </FieldGroup>
        </Form>
        <Result>
            <Layout>
                <SplitPanel/>
            </Layout>
        </Result>
    </SearchType>
</Project>
%
</blockquote>

When adding a new project to Hydra, be sure to also add the project to projectList.xml
(<a href="projectList.dtd.html">projectList.dtd</a>):
<blockquote>
%
<ProjectList>
    ...
    <ProjectItem id="hWorld" active="true">
        <Display>Hello World!</Display>
        <Tooltip>Hello World Test</Tooltip>
        <ConfigFile>test/hWorld.xml</ConfigFile>
    </ProjectItem>
</ProjectList>
%
</blockquote> 
 -->
<!ELEMENT  Project (Name, Title, Properties?, OverrideProperties?, Catalog*, SearchGroup*)>

<!-- Defines grouping among the SearchType -->
<!ELEMENT  SearchGroup (Name, Title, SearchType*)>

<!-- Defines optional Catalog entries to be prepended to list of regular catalogs for Catalog Search dialog -->
<!ELEMENT  Catalog (Host, Credentials?, CatalogURL, OriginalFilename, MasterCatFilename, AddtlReqSearchParams?)>
<!--
     @attr name The name of the catalog that will be prepended to the public list.  Ex: WISEPASS1
-->
<!ATTLIST    Catalog name CDATA #IMPLIED>

<!ELEMENT  Host (#PCDATA)>

<!ELEMENT  Credentials EMPTY>
<!ATTLIST    Credentials login CDATA #IMPLIED>
<!ATTLIST    Credentials password CDATA #IMPLIED>

<!ELEMENT  CatalogURL (#PCDATA)>

<!ELEMENT  OriginalFilename (#PCDATA)>

<!ELEMENT  MasterCatFilename (#PCDATA)>

<!ELEMENT  AddtlReqSearchParams (GatorParam*)>

<!ELEMENT  GatorParam EMPTY>
<!ATTLIST    GatorParam requestName CDATA #IMPLIED>
<!ATTLIST    GatorParam masterCatName CDATA #IMPLIED>


<!-- Defines the search type properties and attributes. -->
<!ELEMENT  SearchType (Name, Title, Tooltip?, Access?, (CommandId|(Form, Query*, Result?)))>
<!-- An identifier that maps to the help text defined in the index.html file. -->
<!ATTLIST    SearchType helpId CDATA #IMPLIED>
<!ATTLIST    SearchType layoutSelector (true|false) "false">

<!ELEMENT  CommandId (#PCDATA)>

<!ELEMENT  Properties (Param*)>

<!ELEMENT  OverrideProperties (Param*)>

<!ELEMENT  Access EMPTY>
<!-- A comma delimited string of roles. The included roles will allow access to the content. -->
<!ATTLIST    Access includes CDATA #IMPLIED>
<!-- A comma delimited string of roles. The included roles will exclude access to the content. -->
<!ATTLIST    Access excludes CDATA #IMPLIED>

<!--
A searchtype form consists of at least one top level FieldGroup container, and may optionally define
FormEventWorkers that add custom behavior to the form.
-->
<!ELEMENT  Form (FormEventWorker*, FieldGroup+)>
<!ATTLIST    Form title CDATA #IMPLIED>
<!ATTLIST    Form minSize CDATA #IMPLIED>
<!ATTLIST    Form helpId CDATA #IMPLIED>

<!ELEMENT  Query (Constraints?, Param*, Metadata?, Download?)>
<!ATTLIST    Query xid CDATA #IMPLIED>
<!ATTLIST    Query ref-xid CDATA #IMPLIED>
<!ATTLIST    Query id CDATA #REQUIRED>
<!-- A string that identifies which search processor to use. Possible search processors are: "SearchBCD", "WiseQuery", "WiseQueryArtifact", "WIseFileRetrieve", "PlanckImagesQuery", "GatorQuery", "2MassQuery", "2MassQueryArtifact" and "2MassFileRetrieve", -->
<!ATTLIST    Query searchProcessorId CDATA #IMPLIED>

<!ELEMENT  Constraints (Condition|And|Or)>
<!ELEMENT  And (Condition+, Or?)>
<!ELEMENT  Or (Condition+, And?)>
<!ELEMENT  Condition EMPTY>
<!ATTLIST    Condition fieldDefVisible CDATA #IMPLIED>
<!ATTLIST    Condition fieldDefHidden CDATA #IMPLIED>
<!ATTLIST    Condition fieldDefId CDATA #IMPLIED>
<!ATTLIST    Condition value CDATA #IMPLIED>

<!-- This popup panel provides an interface for downloading catalog and image files. -->
<!ELEMENT  Download (Param*, SearchFormParam*, Form?)>
<!ATTLIST    Download id CDATA #REQUIRED>
<!ATTLIST    Download title CDATA #IMPLIED>
<!ATTLIST    Download filePrefix CDATA #IMPLIED>
<!ATTLIST    Download titlePrefix CDATA #IMPLIED>
<!ATTLIST    Download maxRows CDATA #IMPLIED>

<!-- This panel provides search results data. The data can be shown in table or text form. -->
<!ELEMENT  Result (EventWorker*, Layout)>
<!ATTLIST    Result xid CDATA #IMPLIED>
<!ATTLIST    Result ref-xid CDATA #IMPLIED>

<!-- This panel provides ... -->
<!ELEMENT  FieldGroup (Title?, Tooltip?, Access?, (FieldGroup|PreDefField|Label|HIDDEN|String|Date|DEGREE|Double|Float|EMail|EnumString|Integer|Password|Pattern|Lat|Lon|MultiCoord|File|Help)*)>
<!ATTLIST    FieldGroup xid CDATA #IMPLIED>
<!ATTLIST    FieldGroup ref-xid CDATA #IMPLIED>
<!-- A string defining the FieldGroup's panel type. -->
<!ATTLIST    FieldGroup type (default|tabPane|activeTabPane|collapsiblePanel|activeCollapsiblePanel|datePanel|frame) "default">
<!ATTLIST    FieldGroup typeName CDATA #IMPLIED>
<!ATTLIST    FieldGroup labelWidth CDATA "100">
<!ATTLIST    FieldGroup direction (vertical|horizontal) "vertical">
<!ATTLIST    FieldGroup width CDATA #IMPLIED>
<!ATTLIST    FieldGroup height CDATA #IMPLIED>
<!ATTLIST    FieldGroup spacing CDATA "0">
<!ATTLIST    FieldGroup align (left|center|right) "right">
<!ATTLIST    FieldGroup downloadRestriction CDATA #IMPLIED>

<!-- This element defines the pre-defined fields for inputing parameters. -->
<!ELEMENT  PreDefField (Param*)>
<!-- A string that identitfies one of the available pre-defined inputs. Possible preDefField values are: "targetPanel", "RangePanel", "catalogPopupPanel", ... -->
<!ATTLIST    PreDefField id CDATA #REQUIRED>

<!ELEMENT  HIDDEN (ID?, Name, Default)>
<!ELEMENT  String (ID?, Name, Title, PreferWidth?, Icon?, Default?, Pref-Key?, Mask?, MaxWidth?, Cached?, NullAllowed?, LongDescription?, ShortDescription?, ErrorDescription?)>
<!ELEMENT  Date (ID?, Name, Title, Icon?, Default?, Pref-Key?, Mask?, PreferWidth?, MaxWidth?, Min?, Max?, Cached?, Format*, NullAllowed?, LongDescription?, ShortDescription?, ErrorDescription?)>
<!ATTLIST    Date minBoundType (exclusive|inclusive|undefined) "undefined">
<!ATTLIST    Date maxBoundType (exclusive|inclusive|undefined) "undefined">
<!ELEMENT  DEGREE (ID?, Name, Title, Default?, PreferWidth?, LongDescription?, ShortDescription?, ErrorDescription?, Icon?, Mask?, PreferWidth?, MaxWidth?, Min?, Max?, Cached?, NullAllowed?)>
<!ATTLIST    DEGREE units (degree|arcmin|arcsec) "degree">
<!ELEMENT  Double (ID?, Name, Title, LongDescription?, ShortDescription?, Icon?, Default?, Pref-Key?, ErrorDescription?, Mask?, MaxWidth?, Min?, Max?, Precision?, Cached?, NullAllowed?)>
<!ATTLIST    Double scientificAllowed (true|false) "false">
<!ATTLIST    Double minBoundType (exclusive|inclusive|undefined) "undefined">
<!ATTLIST    Double maxBoundType (exclusive|inclusive|undefined) "undefined">
<!ELEMENT  Float (ID?, Name, Title, LongDescription?, ShortDescription?, Icon?, Default?, Pref-Key?, ErrorDescription?, Mask?, PreferWidth?, MaxWidth?, Min?, Max?, Precision?, Cached?, NullAllowed?)>
<!ATTLIST    Float scientificAllowed (true|false) "false">
<!ATTLIST    Float minBoundType (exclusive|inclusive|undefined) "undefined">
<!ATTLIST    Float maxBoundType (exclusive|inclusive|undefined) "undefined">
<!ELEMENT  EMail (ID?, Name, Title, LongDescription?, ShortDescription?, Icon?, Default?, Pref-Key?, ErrorDescription?, Mask?, PreferWidth?, MaxWidth?, Cached?, NullAllowed?)>
<!ELEMENT  EnumString (ID?, Name, Title, PreferWidth?, Mask?, Default?, MaxWidth?, Icon?,Pref-Key?, Cached?, NullAllowed?, LongDescription?, ShortDescription?, ErrorDescription?, EnumValue+)>
<!ATTLIST    EnumString orientation (horizontal|vertical) "horizontal">
<!ELEMENT  Integer (ID?, Name, Title, LongDescription?, ShortDescription?, Icon?, Default?, Pref-Key?, ErrorDescription?, Mask?, PreferWidth?, MaxWidth?, Cached?, NullAllowed?)>
<!ELEMENT  Lat (ID?, Name, Title, LongDescription?, ShortDescription?, Icon?, Default?, ErrorDescription?, Mask?, PreferWidth?, MaxWidth?, Cached?, NullAllowed?)>
<!ELEMENT  Lon (ID?, Name, Title, LongDescription?, ShortDescription?, Icon?, Default?, ErrorDescription?, Mask?, PreferWidth?, MaxWidth?, Cached?, NullAllowed?)>
<!ELEMENT  MultiCoord (ID?, Name, Title, LongDescription?, ShortDescription?, Icon?, Default?, ErrorDescription?, Mask?, PreferWidth?, MaxWidth?, Cached?, NullAllowed?)>
<!ELEMENT  Password (ID?, Name, Title, LongDescription?, ShortDescription?, Icon?, Default?, ErrorDescription?, Mask?, PreferWidth?, MaxWidth?, Cached?, NullAllowed?)>
<!ELEMENT  Pattern (ID?, Name, Title, PreferWidth?, Icon?, Default?, Pref-Key?, Mask?, ValidateMask?, MaxWidth?, Cached?, NullAllowed?, LongDescription?, ShortDescription?, ErrorDescription?)>
<!ELEMENT  File (ID?, Name, Title, Icon?, Default?, Mask?, PreferWidth?, MaxWidth?, Cached?, Size?, LongDescription?, ShortDescription?, ErrorDescription?)>
<!ELEMENT  Help (Title)>
<!ATTLIST    Help helpId CDATA #REQUIRED>
<!ELEMENT  EnumValue (Title, ShortDescription?, IntValue?)>
<!ATTLIST    EnumValue id CDATA #REQUIRED>

<!-- Defines the layout of the panel -->
<!ELEMENT  Layout (SplitPanel)>

<!-- Defines the position and orientation of the split panel. -->
<!ELEMENT  SplitPanel ((North|West|East|South)*, Center)>
<!ATTLIST    SplitPanel xid CDATA #IMPLIED>
<!ATTLIST    SplitPanel ref-xid CDATA #IMPLIED>

<!-- Defines the results panel position and type. North will postion the panel along the top of the display. -->
<!ELEMENT  North ((Table|Preview|Form|SplitPanel|HtmlLoader)*)>
<!ATTLIST    North layout (horizontal|vertical|tab|fixedTab) "horizontal">
<!ATTLIST    North title CDATA #IMPLIED>
<!ATTLIST    North initialHeight CDATA #IMPLIED>
<!ATTLIST    North groupId CDATA #IMPLIED>
<!ATTLIST    North helpId CDATA #IMPLIED>
<!ATTLIST    North tagIt (true|false) "false">

<!-- Defines the results panel position and type. West will postion the panel along the left side of the display. -->
<!ELEMENT  West ((Table|Preview|Form|SplitPanel|HtmlLoader)*)>
<!ATTLIST    West layout (horizontal|vertical|tab|fixedTab) "horizontal">
<!ATTLIST    West title CDATA #IMPLIED>
<!ATTLIST    West initialWidth CDATA #IMPLIED>
<!ATTLIST    West groupId CDATA #IMPLIED>
<!ATTLIST    West helpId CDATA #IMPLIED>
<!ATTLIST    West tagIt (true|false) "false">

<!-- Defines the results panel position and type. -->
<!ELEMENT  Center (Table|Preview|Form|SplitPanel|HtmlLoader)+>
<!ATTLIST    Center layout (horizontal|vertical|tab|fixedTab) "horizontal">
<!ATTLIST    Center layoutName CDATA #IMPLIED>
<!ATTLIST    Center title CDATA #IMPLIED>
<!ATTLIST    Center groupId CDATA #IMPLIED>
<!ATTLIST    Center helpId CDATA #IMPLIED>
<!ATTLIST    Center tagIt (true|false) "false">

<!-- Defines the results panel position and type. East will postion the panel along the right side of the display. -->
<!ELEMENT  East ((Table|Preview|Form|SplitPanel|HtmlLoader)*)>
<!ATTLIST    East layout (horizontal|vertical|tab|fixedTab) "horizontal">
<!ATTLIST    East title CDATA #IMPLIED>
<!ATTLIST    East initialWidth CDATA #IMPLIED>
<!ATTLIST    East groupId CDATA #IMPLIED>
<!ATTLIST    East helpId CDATA #IMPLIED>
<!ATTLIST    East tagIt (true|false) "false">

<!-- Defines the results panel position and type. South will postion the panel along the bottom of the display. -->
<!ELEMENT  South ((Table|Preview|Form|SplitPanel|HtmlLoader)*)>
<!ATTLIST    South layout (horizontal|vertical|tab|fixedTab) "horizontal">
<!ATTLIST    South title CDATA #IMPLIED>
<!ATTLIST    South initialHeight CDATA #IMPLIED>
<!ATTLIST    South groupId CDATA #IMPLIED>
<!ATTLIST    South helpId CDATA #IMPLIED>
<!ATTLIST    South tagIt (true|false) "false">

<!--Available Params:
    show-filter (true|false)
    show-options (true|false)
    show-popout (true|false)
    show-title (true|false)
    show-toolbar (true|false)
    show-paging (true|false)
    show-save (true|false)
-->
<!ELEMENT  Table (QueryId, Name?, Title?, ShortDescription?, Width?, Height?, TopIndent?, BottomIndent?, LeftIndent?, RightIndent?, Param*, View*)>
<!ATTLIST    Table xid CDATA #IMPLIED>
<!ATTLIST    Table ref-xid CDATA #IMPLIED>
<!ATTLIST    Table id CDATA #IMPLIED>
<!ATTLIST    Table align (center|left|right) "left">
<!ATTLIST    Table type CDATA #REQUIRED>

<!ELEMENT  View (QueryId?, Name, ShortDescription?, Index?, Param*)>
<!ATTLIST    View id CDATA #IMPLIED>
<!ATTLIST    View type (ImageGridView|XYTableView) "ImageGridView">

<!ELEMENT  Preview (Constraints?, QueryId*, EventWorkerId*, Title?, ShortDescription?, Width?, Height?, TopIndent?, BottomIndent?, LeftIndent?, RightIndent?, Param*)>
<!ATTLIST    Preview xid CDATA #IMPLIED>
<!ATTLIST    Preview ref-xid CDATA #IMPLIED>
<!ATTLIST    Preview id CDATA #IMPLIED>
<!ATTLIST    Preview align (center|left|right) "left">
<!ATTLIST    Preview frameType (titleFrame|frameOnly|noFrame) "frameOnly">
<!ATTLIST    Preview type CDATA #REQUIRED>

<!--
FormEventWorkers add custom behavior to the form outside of the normal behavior provided by Firefly.  Custom behavior may include
hiding or showing certain fields based on values of other fields, or resizing tab panes, etc.  Each FormEventWorker requires a
different set of Param key/value configuration settings for proper functionality.  See below.

FieldDefVisibilityControl parameters:
  masters:
  show:
  hide:
  retainSpace:

CollapsiblePanelVisibilityControl parameters:
  masters:
  slaves:

TabPaneSizeControl parameters:
  tabPaneName:
  <tab name>:
-->
<!ELEMENT  FormEventWorker (ShortDescription?, Param*, FieldDefIds?)>
<!--
  @attr id (required) The ID associated with this FormEventWorker
  @attr type (required) The type of FormEventWorker.  Firefly contains the following FormEventWorkers: FieldDefVisibilityControl, CollapsiblePanelVisibilityControl,
             TabPaneSizeControl, FieldChangeControl.  WISE additionally has the following custom FormEventWorkers: WisePreviewControl
  @attr xid (optional) XML object storage ID.  Used internally to save XML objects for subsequent referencing
  @attr ref-xid (optional) XML object retrieval ID.  Used internally to reference previously-stored XML objects
-->
<!ATTLIST FormEventWorker
    id CDATA #REQUIRED
    type CDATA #REQUIRED
    xid CDATA #IMPLIED
    ref-xid CDATA #IMPLIED
>

<!ELEMENT  HtmlLoader (QueryId, Label?, Param*)>

<!ELEMENT  EventWorker (QueryId*, ShortDescription?, Param*)>
<!ATTLIST    EventWorker xid CDATA #IMPLIED>
<!ATTLIST    EventWorker ref-xid CDATA #IMPLIED>
<!ATTLIST    EventWorker id CDATA #REQUIRED>
<!ATTLIST    EventWorker type CDATA #REQUIRED>

<!ELEMENT  Metadata (Param*)>

<!ELEMENT  FieldDefIds (Param*)>

<!ELEMENT  QueryId (#PCDATA)>

<!ELEMENT  EventWorkerId (#PCDATA)>

<!-- Used for passing key-value pair data to the server. -->
<!ELEMENT  Param EMPTY>
<!-- A key mapping to a single value, duplicate keys are not allowed. -->
<!ATTLIST    Param key CDATA #REQUIRED>
<!ATTLIST    Param value CDATA #REQUIRED>

<!ELEMENT  SearchFormParam EMPTY>
<!ATTLIST    SearchFormParam keyName CDATA #REQUIRED>
<!ATTLIST    SearchFormParam keyValue CDATA #REQUIRED>
<!ATTLIST    SearchFormParam createParams CDATA #REQUIRED>

<!ELEMENT  Cached EMPTY>
<!ELEMENT  NullAllowed EMPTY>

<!ELEMENT  Label (#PCDATA)>
<!ELEMENT  ID (#PCDATA)>
<!ELEMENT  Name (#PCDATA)>
<!ELEMENT  Title (#PCDATA)>
<!ATTLIST  Title  width CDATA #IMPLIED>
<!ELEMENT  Tooltip (#PCDATA)>
<!ELEMENT  LongDescription (#PCDATA)>
<!ELEMENT  ShortDescription (#PCDATA)>
<!ELEMENT  Icon (#PCDATA)>
<!ELEMENT  Default (#PCDATA)>
<!ELEMENT  Pref-Key (#PCDATA)>
<!ELEMENT  ErrorDescription (#PCDATA)>
<!ELEMENT  Mask (#PCDATA)>
<!ELEMENT  ValidateMask (#PCDATA)>
<!ELEMENT  PreferWidth (#PCDATA)>
<!ELEMENT  Size (#PCDATA)>
<!ELEMENT  MaxWidth (#PCDATA)>
<!ELEMENT  Value (#PCDATA)>
<!ELEMENT  IntValue (#PCDATA)>
<!ELEMENT  Index (#PCDATA)>

<!ELEMENT  Format (#PCDATA)>
<!ELEMENT  Min (#PCDATA)>
<!ELEMENT  Max (#PCDATA)>
<!ELEMENT  Precision (#PCDATA)>

<!-- Defines the width of the pane. -->
<!ELEMENT  Width (#PCDATA)>
<!-- Defines the height of the pane. -->
<!ELEMENT  Height (#PCDATA)>
<!ELEMENT  TopIndent (#PCDATA)>
<!ELEMENT  BottomIndent (#PCDATA)>
<!ELEMENT  LeftIndent (#PCDATA)>
<!ELEMENT  RightIndent (#PCDATA)>


<!ELEMENT xi:include EMPTY>
<!ATTLIST xi:include
    xmlns:xi   CDATA       #FIXED    "http://www.w3.org/2001/XInclude"
    href       CDATA       #REQUIRED
    parse      (xml|text)  "xml"
>

=== Caltech-IPAC/firefly/config/hydra/configurable/wise/qry_1b.xml
<!DOCTYPE Query SYSTEM "../../project.dtd" [
        <!ENTITY few_dl_fields_visi         SYSTEM "few_dl_fields_visi.xml.txt">
        <!ENTITY prm_l1_cols_meta           SYSTEM "prm_l1_common_meta.xml.txt">
        ]>

<Query id="wiseQuery_1b" searchProcessorId="WiseQuery" xid="wiseQuery_1b">
    <Constraints>
        <And>
            <Condition fieldDefHidden="filename"/>
            <Condition fieldDefId="optLevel" value="1b"/>
        </And>
    </Constraints>
    <Param key="host" value="%wise.ibe.host%"/>
    <Param key="schemaGroup" value="wise"/>
    <!--<Param key="table" value="i1bm_frm"/>-->
    <Param key="ProductLevel" value="1b"/>
    <!--<Param key="SourceTable" value="i1bs_psd"/>-->
    <Param key="SortInfo" value="SortInfo=ASC,scan_id,frame_num,band"/>
    <Metadata>
        &prm_l1_cols_meta;
        <Param key="host" value="%wise.ibe.host%"/>
        <Param key="schemaGroup" value="wise"/>
        <Param key="ProductLevel" value="1b"/>
        <Param key="table" value="i1bm_frm"/>
    </Metadata>
    <Download id="WiseDownload" title="Download Options" filePrefix="WISE_Files" titlePrefix="WISE" maxRows="5000">
        <Param key="host" value="%wise.ibe.host%"/>
        <Param key="schemaGroup" value="wise"/>
        <!--<Param key="table" value="i1bm_frm"/>-->
        <Param key="ProductLevel" value="1b"/>
        <SearchFormParam keyName="subsize" keyValue="*" createParams="subsize,UserTargetWorldPt"/>
        <Form>
            &few_dl_fields_visi;
            <FieldGroup labelWidth="130">
                <xi:include href="f_allBands.xml"/>
                <xi:include href="f_L1_artFiles.xml"/>
                <xi:include href="fg_dlCutouts.xml"/>
                <xi:include href="f_zipType.xml"/>
                <Label><![CDATA[&nbsp;]]></Label>
            </FieldGroup>
        </Form>
    </Download>
</Query>

=== Caltech-IPAC/firefly/config/hydra/configurable/wise/f_L1_artFiles.xml
<!DOCTYPE EnumString SYSTEM "../../project.dtd">

<EnumString orientation="horizontal">
    <Name>artFiles</Name>
    <Title>Download Ancillary Files:</Title>
    <PreferWidth>400</PreferWidth>
    <Mask>[CHECKBOX]</Mask>
    <Default>_none_</Default>
    <NullAllowed/>
    <ShortDescription>Download Ancillary Files</ShortDescription>
    <EnumValue id="M">
        <Title>Mask</Title>
    </EnumValue>
    <EnumValue id="U">
        <Title>Uncertainty</Title>
    </EnumValue>
    <EnumValue id="D">
        <Title>Diffraction Spikes</Title>
    </EnumValue>
    <EnumValue id="H">
        <Title>Halos</Title>
    </EnumValue>
    <EnumValue id="O">
        <Title>Optical Ghosts</Title>
    </EnumValue>
    <EnumValue id="P">
        <Title>Latents</Title>
    </EnumValue>
</EnumString>

=== Caltech-IPAC/firefly/config/hydra/configurable/wise/f_subsize.xml
<!DOCTYPE DEGREE SYSTEM "../../project.dtd">

<DEGREE units="arcsec">
    <Name>subsize</Name>
    <Title>Return Image Size (leave blank for full images)</Title>
    <Default>600</Default>
    <PreferWidth>16</PreferWidth>
    <ShortDescription>Specifies the size of the desired L1b or Atlas image cutout. Omitting this constraint will result in visualization/return of entire L1b/Atlas images.

In multi-input mode, this takes effect only for input tables without a subsize column.</ShortDescription>
    <ErrorDescription>Invalid entry!</ErrorDescription>
    <Min>1</Min>
    <Max>7200</Max>
    <NullAllowed/>
</DEGREE>

=== Caltech-IPAC/firefly/config/hydra/configurable/wise/fg_L1_addtl_opts.xml
<!DOCTYPE FieldGroup SYSTEM "../../project.dtd">

<FieldGroup type="activeCollapsiblePanel" typeName="L1" labelWidth="200">
    <Title>Optional constraints for Single Exposure (Level 1b) data</Title>
    <FieldGroup labelWidth="580">
        <FieldGroup direction="horizontal" labelWidth="130">
            <Date>
                <Name>timeStart</Name>
                <Title>Start Date (UT)</Title>
                <Format>yyyy-MM-dd;yyyy-MM-dd HH:mm:ss</Format>
                <NullAllowed/>
                <ShortDescription>Period start (yyyy-MM-dd [HH:mm:ss])</ShortDescription>
                <ErrorDescription>Format error!</ErrorDescription>
            </Date>
            <Date>
                <Name>timeEnd</Name>
                <Title>End Date (UT)</Title>
                <Format>yyyy-MM-dd;yyyy-MM-dd HH:mm:ss</Format>
                <NullAllowed/>
                <ShortDescription>Period end (yyyy-MM-dd [HH:mm:ss])</ShortDescription>
                <ErrorDescription>Format error!</ErrorDescription>
            </Date>
        </FieldGroup>
        <Label>
            <![CDATA[<i>&nbsp;&nbsp;&nbsp;&nbsp;Enter date range to search, format example: </i>2010-01-10 15:30:00<i>, or </i>2010-01-10<i>.</i><br><br>]]></Label>
    </FieldGroup>
    <FieldGroup align="left" labelWidth="144">
        <String>
            <Name>scanId</Name>
            <Title>Scan ID(s)</Title>
            <PreferWidth>50</PreferWidth>
            <NullAllowed/>
            <ShortDescription>Optionally provide one of more WISE scan identifier(s) separated by space or comma: 00712a, 01432a, 05693b.  Together with an in-scan frame number, scan ID uniquely identifies a single epoch WISE image set .</ShortDescription>
        </String>
        <FieldGroup direction="horizontal" labelWidth="144">
            <EnumString orientation="vertical">
                <Name>frameOp</Name>
                <Title>Frame Number(s) (optional)</Title>
                <Default>eq</Default>
                <NullAllowed/>
                <ShortDescription>A WISE L1b image frame number or an acceptable frame number range may be provided.

In multi-input mode, these constraints apply only if the input table does not have a frame_min or frame_max column.

Frame numbers are non-negative integers uniquely identifying an image set within a specific scan.</ShortDescription>
                <EnumValue id="eq">
                    <Title>=</Title>
                </EnumValue>
                <EnumValue id="gt">
                    <Title>&gt;</Title>
                </EnumValue>
                <EnumValue id="lt">
                    <Title>&lt;</Title>
                </EnumValue>
                <EnumValue id="in">
                    <Title>IN</Title>
                </EnumValue>
                <EnumValue id="be">
                    <Title>BETWEEN</Title>
                </EnumValue>
            </EnumString>
            <FieldGroup align="left" direction="horizontal" labelWidth="1">
                <Label><![CDATA[<div style='width:18px'>&nbsp;</div]]></Label>
                <String>
                    <Name>frameVal1</Name>
                    <Title></Title>
                    <PreferWidth>10</PreferWidth>
                    <NullAllowed/>
                    <ShortDescription>Enter frame number</ShortDescription>
                </String>
                <String>
                    <Name>frameVal2</Name>
                    <Title></Title>
                    <PreferWidth>10</PreferWidth>
                    <NullAllowed/>
                    <ShortDescription>Enter end frame number</ShortDescription>
                </String>
                <String>
                    <Name>frameVal3</Name>
                    <Title></Title>
                    <PreferWidth>30</PreferWidth>
                    <NullAllowed/>
                    <ShortDescription>Enter list of frame numbers</ShortDescription>
                </String>
            </FieldGroup>
        </FieldGroup>
    </FieldGroup>
</FieldGroup>

=== Caltech-IPAC/firefly/config/hydra/configurable/wise/fg_optlvl_1b.xml
<!DOCTYPE FieldGroup SYSTEM "../../project.dtd">

<FieldGroup xid="optLevel_1b" labelWidth="140">
    <EnumString orientation="horizontal">
        <ID>optLevel_1b</ID>
        <Name>optLevel</Name>
        <Title>Data Product Level:</Title>
        <PreferWidth>300</PreferWidth>
        <Mask>[RADIO]</Mask>
        <Default>1b</Default>
        <ShortDescription>Data Product Level</ShortDescription>
        <ErrorDescription>Select at least one product!</ErrorDescription>
        <EnumValue id="1b">
            <Title>Single Exposure</Title>
        </EnumValue>
    </EnumString>
</FieldGroup>

=== Caltech-IPAC/firefly/config/hydra/configurable/wise/fg_dplvl_1b.xml
<!DOCTYPE FieldGroup SYSTEM "../../project.dtd">

<FieldGroup xid="dpLevel_1b" labelWidth="140">
    <EnumString orientation="horizontal">
        <ID>dpLevel_1b</ID>
        <Name>dpLevel</Name>
        <Title>Data Product Level:</Title>
        <PreferWidth>300</PreferWidth>
        <Mask>[RADIO]</Mask>
        <Default>1b</Default>
        <ShortDescription>Data Product Level</ShortDescription>
        <ErrorDescription>Select at least one product!</ErrorDescription>
        <EnumValue id="1b">
            <Title>Single Exposure</Title>
        </EnumValue>
    </EnumString>
</FieldGroup>

=== Caltech-IPAC/firefly/config/hydra/configurable/wise/f_allBands.xml
<!DOCTYPE EnumString SYSTEM "../../project.dtd">

<EnumString orientation="horizontal">
    <Name>allBands</Name>
    <Title>Download All Bands (1-4):</Title>
    <PreferWidth>400</PreferWidth>
    <Mask>[RADIO]</Mask>
    <Default>yes</Default>
    <ShortDescription>Download All Bands</ShortDescription>
    <EnumValue id="yes">
        <Title>Yes</Title>
    </EnumValue>
    <EnumValue id="no">
        <Title>No</Title>
    </EnumValue>
</EnumString>

=== Caltech-IPAC/firefly/config/hydra/configurable/wise/f_zipType.xml
<!DOCTYPE EnumString SYSTEM "../../project.dtd">

<EnumString orientation="vertical">
    <Name>zipType</Name>
    <Title>Zip File Structure</Title>
    <PreferWidth>400</PreferWidth>
    <Default>folder</Default>
    <ShortDescription>Zip File Structure</ShortDescription>
    <EnumValue id="folder">
        <Title>Structured (with folders)</Title>
    </EnumValue>
    <EnumValue id="flat">
        <Title>Flattened (no folders)</Title>
    </EnumValue>
</EnumString>
