=== Caltech-IPAC/firefly/src/fftools/config/configurable/Mission.dtd
<!ELEMENT  Mission (Title, SpacialTypes?, Desc?, CatalogSet*, ImageSet*, Spectrum*)>
<!ATTLIST    Mission name CDATA #REQUIRED>
<!ATTLIST    Mission dataTypes CDATA #IMPLIED>      <!-- comma separated types.. imageset,catalog,spectrum -->

<!-- comma separated values -->
<!--Cone|Elliptical|Box|Polygon|MultiTableUpload|MultiPrevSearch|MultiPoints|AllSky-->
<!ELEMENT  SpacialTypes EMPTY>
<!ATTLIST    SpacialTypes catalog CDATA #IMPLIED>
<!ATTLIST    SpacialTypes spectrum CDATA #IMPLIED>
<!ATTLIST    SpacialTypes imageSet CDATA #IMPLIED>

<!ENTITY % dataSetElements
        "Title, Desc?, DataSource?, Form?, Download?, ActiveTarget?"
        >

<!ELEMENT  ImageSet (%dataSetElements;, Artifact*, Image?)>
<!ATTLIST    ImageSet name CDATA #REQUIRED>
<!ATTLIST    ImageSet datasetInfoConverterId CDATA #IMPLIED>

<!ELEMENT  CatalogSet (%dataSetElements;, Coverage?, Image?)>
<!ATTLIST    CatalogSet name CDATA #REQUIRED>
<!ATTLIST    CatalogSet datasetInfoConverterId CDATA #IMPLIED>

<!ELEMENT  Spectrum (%dataSetElements;)>
<!ATTLIST    Spectrum name CDATA #REQUIRED>
<!ATTLIST    Spectrum datasetInfoConverterId CDATA #IMPLIED>

<!ELEMENT  DataSource (IBE?, TAP?, Param*)>
<!ATTLIST    DataSource searchProcId CDATA #IMPLIED>
<!ATTLIST    DataSource argColUrl CDATA #IMPLIED>
<!ATTLIST    DataSource argHeaderUrl CDATA #IMPLIED>

<!ELEMENT  IBE EMPTY>
<!ATTLIST    IBE baseUrl CDATA #IMPLIED>
<!ATTLIST    IBE action     (search|data|docs) "search">
<!ATTLIST    IBE mission    CDATA #IMPLIED>
<!ATTLIST    IBE dataSet    CDATA #IMPLIED>
<!ATTLIST    IBE tableName  CDATA #IMPLIED>

<!ELEMENT  TAP EMPTY>
<!ATTLIST    TAP baseUrl    CDATA #IMPLIED>
<!ATTLIST    TAP queryStr   CDATA #IMPLIED>

<!-- Used for passing key-value pair data to the server. -->
<!ELEMENT  Param EMPTY>
<!-- A key mapping to a single value, duplicate keys are not allowed. -->
<!ATTLIST    Param key CDATA #REQUIRED>
<!ATTLIST    Param value CDATA #REQUIRED>

<!ELEMENT  Form (FormEventWorker*, FieldGroup+)>
<!ATTLIST    Form title CDATA #IMPLIED>
<!ATTLIST    Form minSize CDATA #IMPLIED>
<!ATTLIST    Form helpId CDATA #IMPLIED>

<!ELEMENT  ActiveTarget EMPTY>
<!ATTLIST    ActiveTarget TargetType (TableRow) "TableRow">
<!ATTLIST    ActiveTarget TargetColumns CDATA #IMPLIED>

<!ELEMENT  Artifact (DataSource?, Param*)>
<!ATTLIST    Artifact ArgCols CDATA #IMPLIED>
<!ATTLIST    Artifact ArgHeaders CDATA #IMPLIED>
<!ATTLIST    Artifact Title CDATA #IMPLIED>
<!ATTLIST    Artifact SYMBOL CDATA #IMPLIED>
<!ATTLIST    Artifact COLOR CDATA #IMPLIED>
<!ATTLIST    Artifact EnablingPreference CDATA #IMPLIED>

<!ELEMENT  Image (DataSource?)>
<!ATTLIST    Image ArgCols CDATA #IMPLIED>
<!ATTLIST    Image ArgHeaders CDATA #IMPLIED>
<!ATTLIST    Image Title CDATA #IMPLIED>
<!ATTLIST    Image Zoom CDATA #IMPLIED>
<!ATTLIST    Image Stretch CDATA #IMPLIED>
<!ATTLIST    Image CenterOnQueryTarget CDATA #IMPLIED>
<!ATTLIST    Image ColorTableId CDATA #IMPLIED>
<!ATTLIST    Image PlotGroup CDATA #IMPLIED>
<!ATTLIST    Image LockRelated CDATA #IMPLIED>
<!ATTLIST    Image RememberPrefs CDATA #IMPLIED>
<!ATTLIST    Image MinSize CDATA #IMPLIED>

<!ELEMENT  Coverage EMPTY>
<!ATTLIST    Coverage Title CDATA #IMPLIED>
<!ATTLIST    Coverage CenterColumns CDATA #IMPLIED>
<!ATTLIST    Coverage CornerColumns CDATA #IMPLIED>




<!--
FormEventWorkers add custom behavior to the form outside of the normal behavior provided by Firefly.  Custom behavior may include
hiding or showing certain fields based on values of other fields, or resizing tab panes, etc.  Each FormEventWorker requires a
different set of Param key/value configuration settings for proper functionality.  See below.

FieldDefVisibilityControl parameters:
  masters:
  show:
  hide:
  retainSpace:

CollapsiblePanelVisibilityControl parameters:
  masters:
  slaves:

TabPaneSizeControl parameters:
  tabPaneName:
  <tab name>:
-->
<!ELEMENT  FormEventWorker (ShortDescription?, Param*)>
<!--
  @attr id (required) The ID associated with this FormEventWorker
  @attr type (required) The type of FormEventWorker.  Firefly contains the following FormEventWorkers: FieldDefVisibilityControl, CollapsiblePanelVisibilityControl,
             TabPaneSizeControl, FieldChangeControl.  WISE additionally has the following custom FormEventWorkers: WisePreviewControl
  @attr xid (optional) XML object storage ID.  Used internally to save XML objects for subsequent referencing
  @attr ref-xid (optional) XML object retrieval ID.  Used internally to reference previously-stored XML objects
-->
<!ATTLIST FormEventWorker
    id CDATA #REQUIRED
    type CDATA #REQUIRED
    xid CDATA #IMPLIED
    ref-xid CDATA #IMPLIED
>

<!-- This popup panel provides an interface for downloading catalog and image files. -->
<!ELEMENT  Download (Form?, Param*)>
<!ATTLIST    Download id CDATA #REQUIRED>
<!ATTLIST    Download title CDATA #IMPLIED>
<!ATTLIST    Download filePrefix CDATA #IMPLIED>
<!ATTLIST    Download titlePrefix CDATA #IMPLIED>
<!ATTLIST    Download maxRows CDATA #IMPLIED>

<!-- This panel provides ... -->
<!ELEMENT  FieldGroup (Title?, Tooltip?, Access?, (FieldGroup|PreDefField|Label|HIDDEN|String|Date|DEGREE|Double|Float|EMail|EnumString|Integer|Password|Pattern|Lat|Lon|MultiCoord|File|Help)*)>
<!ATTLIST    FieldGroup xid CDATA #IMPLIED>
<!ATTLIST    FieldGroup ref-xid CDATA #IMPLIED>
<!-- A string defining the FieldGroup's panel type. -->
<!ATTLIST    FieldGroup type (default|tabPane|activeTabPane|collapsiblePanel|activeCollapsiblePanel|datePanel|frame) "default">
<!ATTLIST    FieldGroup typeName CDATA #IMPLIED>
<!ATTLIST    FieldGroup labelWidth CDATA "100">
<!ATTLIST    FieldGroup direction (vertical|horizontal) "vertical">
<!ATTLIST    FieldGroup width CDATA #IMPLIED>
<!ATTLIST    FieldGroup height CDATA #IMPLIED>
<!ATTLIST    FieldGroup spacing CDATA "0">
<!ATTLIST    FieldGroup align (left|center|right) "right">
<!ATTLIST    FieldGroup downloadRestriction CDATA #IMPLIED>

<!-- This element defines the pre-defined fields for inputing parameters. -->
<!ELEMENT  PreDefField (Param*)>
<!-- A string that identitfies one of the available pre-defined inputs. Possible preDefField values are: "targetPanel", "RangePanel", "catalogPopupPanel", ... -->
<!ATTLIST    PreDefField id CDATA #REQUIRED>

<!ELEMENT  Access EMPTY>
<!-- A comma delimited string of roles. The included roles will allow access to the content. -->
<!ATTLIST    Access includes CDATA #IMPLIED>
<!-- A comma delimited string of roles. The included roles will exclude access to the content. -->
<!ATTLIST    Access excludes CDATA #IMPLIED>


<!ENTITY % fieldElements
        "ID?, Name, Title, PreferWidth?, Icon?, Default?, Pref-Key?, Mask?, MaxWidth?, NullAllowed?, LongDescription?, ShortDescription?, ErrorDescription?"
        >
<!ENTITY % boundTypes
        "(exclusive|inclusive|undefined) 'undefined'"
        >

<!ELEMENT  HIDDEN (ID?, Name, Default)>
<!ELEMENT  String (%fieldElements;)>
<!ELEMENT  Date (%fieldElements;, Min?, Max?, Format*)>
<!ATTLIST    Date minBoundType %boundTypes;>
<!ATTLIST    Date maxBoundType %boundTypes;>
<!ELEMENT  DEGREE (%fieldElements;, Min?, Max?)>
<!ATTLIST    DEGREE units (degree|arcmin|arcsec) "degree">
<!ELEMENT  Double (%fieldElements;, Min?, Max?, Precision?)>
<!ATTLIST    Double scientificAllowed (true|false) "false">
<!ATTLIST    Double minBoundType %boundTypes;>
<!ATTLIST    Double maxBoundType %boundTypes;>
<!ELEMENT  Float (Min?, Max?, Precision?)>
<!ATTLIST    Float scientificAllowed (true|false) "false">
<!ATTLIST    Float minBoundType %boundTypes;>
<!ATTLIST    Float maxBoundType %boundTypes;>
<!ELEMENT  EMail (%fieldElements;)>
<!ELEMENT  EnumString (%fieldElements;, EnumValue+)>
<!ATTLIST    EnumString orientation (horizontal|vertical) "horizontal">
<!ELEMENT  Integer (%fieldElements;)>
<!ELEMENT  Lat (%fieldElements;)>
<!ELEMENT  Lon (%fieldElements;)>
<!ELEMENT  MultiCoord (%fieldElements;)>
<!ELEMENT  Password (%fieldElements;)>
<!ELEMENT  Pattern (%fieldElements;)>
<!ELEMENT  File (%fieldElements;)>
<!ELEMENT  Help (Title)>
<!ATTLIST    Help helpId CDATA #REQUIRED>
<!ELEMENT  EnumValue (Title, ShortDescription?, IntValue?)>
<!ATTLIST    EnumValue id CDATA #REQUIRED>


<!ELEMENT  NullAllowed EMPTY>

<!ELEMENT  Label (#PCDATA)>
<!ELEMENT  ID (#PCDATA)>
<!ELEMENT  Name (#PCDATA)>
<!ELEMENT  Title (#PCDATA)>
<!ELEMENT  title (#PCDATA)>
<!ATTLIST  Title  width CDATA #IMPLIED>
<!ELEMENT  Tooltip (#PCDATA)>
<!ELEMENT  Desc (#PCDATA)>
<!ELEMENT  desc (#PCDATA)>
<!ELEMENT  LongDescription (#PCDATA)>
<!ELEMENT  ShortDescription (#PCDATA)>
<!ELEMENT  Icon (#PCDATA)>
<!ELEMENT  Default (#PCDATA)>
<!ELEMENT  Pref-Key (#PCDATA)>
<!ELEMENT  ErrorDescription (#PCDATA)>
<!ELEMENT  Mask (#PCDATA)>
<!ELEMENT  ValidateMask (#PCDATA)>
<!ELEMENT  PreferWidth (#PCDATA)>
<!ELEMENT  Size (#PCDATA)>
<!ELEMENT  MaxWidth (#PCDATA)>
<!ELEMENT  Value (#PCDATA)>
<!ELEMENT  IntValue (#PCDATA)>
<!ELEMENT  Format (#PCDATA)>
<!ELEMENT  Min (#PCDATA)>
<!ELEMENT  Max (#PCDATA)>
<!ELEMENT  Precision (#PCDATA)>


<!ELEMENT xi:include EMPTY>
<!ATTLIST xi:include
        xmlns:xi   CDATA       #FIXED    "http://www.w3.org/2001/XInclude"
        href       CDATA       #REQUIRED
        parse      (xml|text)  "xml"
        >

=== Caltech-IPAC/firefly/src/fftools/config/configurable/2mass.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Mission SYSTEM "Mission.dtd">

<Mission name="2mass" dataTypes="ImageSet,Catalog">
    <Title>2MASS</Title>
    <SpacialTypes catalog="Cone,Box" imageSet="Cone"/>
    <Desc>The Two Micron All Sky Survey at IPAC</Desc>

    <ImageSet name="2mass-asky">
        <Title>2MASS All Sky</Title>
        <Desc>2MASS All Sky Release Survey Images</Desc>
        <DataSource searchProcId="ibe_processor">
            <Param key="mission" value="twomass"/>
            <Param key="ds" value="asky"/>
        </DataSource>
        <xi:include href="2mass/2mass_optional.xml"/>
    </ImageSet>
    <ImageSet name="2mass-askyw">
        <Title>2MASS Full Survey</Title>
        <Desc>2MASS 2MASS Full Survey Images</Desc>
        <DataSource searchProcId="ibe_processor">
            <Param key="mission" value="twomass"/>
            <Param key="ds" value="askyw"/>
        </DataSource>
        <xi:include href="2mass/2mass_optional.xml"/>
    </ImageSet>
    <ImageSet name="2mass-sx">
        <Title>2MASS 6X Catalog Images</Title>
        <Desc>2MASS 6X Catalog Images</Desc>
        <DataSource searchProcId="ibe_processor">
            <Param key="mission" value="twomass"/>
            <Param key="ds" value="sx"/>
        </DataSource>
        <xi:include href="2mass/2mass_optional.xml"/>
    </ImageSet>
    <ImageSet name="2mass-sxw">
        <Title>2MASS Full 6X Images</Title>
        <Desc>2MASS Full 6X Images</Desc>
        <DataSource searchProcId="ibe_processor">
            <Param key="mission" value="twomass"/>
            <Param key="ds" value="sxw"/>
        </DataSource>
        <xi:include href="2mass/2mass_optional.xml"/>
    </ImageSet>
    <ImageSet name="2mass-cal">
        <Title>2MASS Calibration Images</Title>
        <Desc>2MASS Calibration Images</Desc>
        <DataSource searchProcId="ibe_processor">
            <Param key="mission" value="twomass"/>
            <Param key="ds" value="cal"/>
        </DataSource>
        <xi:include href="2mass/2mass_optional.xml"/>
    </ImageSet>


</Mission>

=== Caltech-IPAC/firefly/src/fftools/config/configurable/wise.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Mission SYSTEM "Mission.dtd" [
        <!ENTITY few_frameop_visi_cntrl        SYSTEM "wise/few_frameop_visi_cntrl.xml.txt">
        ]>

<Mission name="wise" dataTypes="ImageSet,Catalog">
    <Title>WISE</Title>
    <SpacialTypes catalog="Cone,Box" imageSet="Cone,Box"/>
    <Desc>Wide-field Infrared Survey Explorer (WISE)</Desc>

    <ImageSet name="wise_allwise_3a">
        <Title>AllWISE (milti-band) Atlas</Title>
        <Desc>Search WISE AllWISE Atlas</Desc>
        <DataSource searchProcId="ibe_processor">
            <Param key="mission" value="wise"/>
            <Param key="ImageSet" value="allwise-multiband"/>
            <Param key="ProductLevel" value="3a"/>
        </DataSource>

        <Form>
            <FieldGroup align="left">
                <EnumString>
                    <Name>band</Name>
                    <Title>Return the following bands:</Title>
                    <PreferWidth>150</PreferWidth>
                    <Default>_all_</Default>
                    <Mask>[CHECKBOX]</Mask>
                    <ShortDescription>Band Selection: W1=3.4Œºm, W2=4.6Œºm, W3=12Œºm, W4=22Œºm</ShortDescription>
                    <ErrorDescription>Please select at least one band.</ErrorDescription>
                    <EnumValue id="1">
                        <Title>W1</Title>
                    </EnumValue>
                    <EnumValue id="2">
                        <Title>W2</Title>
                    </EnumValue>
                    <EnumValue id="3">
                        <Title>W3</Title>
                    </EnumValue>
                    <EnumValue id="4">
                        <Title>W4</Title>
                    </EnumValue>
                </EnumString>
            </FieldGroup>
            <xi:include href="wise/wise_3a_optional.xml"/>
        </Form>
        <Artifact ArgCols="scan_id,frame_num,coadd_id,image_set"
                  ArgHeaders="host,mission,dataset,table,ImageSet,ProductLevel"
                  COLOR="yellow"
                  SYMBOL="SQUARE"
                  Title="Halos (squares)">
            <DataSource searchProcId="WiseQueryArtifact">
                <Param key="type" value="H"/>
                <Param key="band" value="2"/>
            </DataSource>
        </Artifact>

    </ImageSet>

    <ImageSet name="wise_allsky_1b">
        <Title>AllSky (4 band) Single Exposure</Title>
        <Desc>Search WISE AllSky Single Exposure</Desc>
        <DataSource searchProcId="ibe_processor">
            <Param key="mission" value="wise"/>
            <Param key="ImageSet" value="allsky_4band"/>
            <Param key="ProductLevel" value="1b"/>
        </DataSource>

        <Form>
            &few_frameop_visi_cntrl;
            <FieldGroup align="left">
                <EnumString>
                    <Name>band</Name>
                    <Title>Return the following bands:</Title>
                    <PreferWidth>150</PreferWidth>
                    <Default>_all_</Default>
                    <Mask>[CHECKBOX]</Mask>
                    <ShortDescription>Band Selection: W1=3.4≈í¬∫m, W2=4.6≈í¬∫m, W3=12≈í¬∫m, W4=22≈í¬∫m</ShortDescription>
                    <ErrorDescription>Please select at least one band.</ErrorDescription>
                    <EnumValue id="1">
                        <Title>W1</Title>
                    </EnumValue>
                    <EnumValue id="2">
                        <Title>W2</Title>
                    </EnumValue>
                    <EnumValue id="3">
                        <Title>W3</Title>
                    </EnumValue>
                    <EnumValue id="4">
                        <Title>W4</Title>
                    </EnumValue>
                </EnumString>
            </FieldGroup>
            <xi:include href="wise/wise_1b_optional.xml"/>
        </Form>
    </ImageSet>

    <ImageSet name="wise_allsky_3a">
        <Title>AllSky (4 band) Atlas</Title>
        <Desc>Search WISE AllSky Atlas</Desc>
        <DataSource searchProcId="ibe_processor">
            <Param key="mission" value="wise"/>
            <Param key="ImageSet" value="allsky_4band"/>
            <Param key="ProductLevel" value="3a"/>
        </DataSource>

        <Form>
            <FieldGroup align="left">
                <EnumString>
                    <Name>band</Name>
                    <Title>Return the following bands:</Title>
                    <PreferWidth>150</PreferWidth>
                    <Default>_all_</Default>
                    <Mask>[CHECKBOX]</Mask>
                    <ShortDescription>Band Selection: W1=3.4Œºm, W2=4.6Œºm, W3=12Œºm, W4=22Œºm</ShortDescription>
                    <ErrorDescription>Please select at least one band.</ErrorDescription>
                    <EnumValue id="1">
                        <Title>W1</Title>
                    </EnumValue>
                    <EnumValue id="2">
                        <Title>W2</Title>
                    </EnumValue>
                    <EnumValue id="3">
                        <Title>W3</Title>
                    </EnumValue>
                    <EnumValue id="4">
                        <Title>W4</Title>
                    </EnumValue>
                </EnumString>
            </FieldGroup>
            <xi:include href="wise/wise_3a_optional.xml"/>
        </Form>
    </ImageSet>

    <ImageSet name="wise_cryo_3band_1b">
        <Title>3-Band Cryo Single Exposure</Title>
        <Desc>Search WISE 3-Band Cryo Single Exposure</Desc>
        <DataSource searchProcId="ibe_processor">
            <Param key="mission" value="wise"/>
            <Param key="ImageSet" value="cryo_3band"/>
            <Param key="ProductLevel" value="1b"/>
        </DataSource>

        <Form>
            &few_frameop_visi_cntrl;
            <FieldGroup align="left">
                <EnumString>
                    <Name>band</Name>
                    <Title>Return the following bands:</Title>
                    <PreferWidth>150</PreferWidth>
                    <Default>_all_</Default>
                    <Mask>[CHECKBOX]</Mask>
                    <ShortDescription>Band Selection: W1=3.4≈í¬∫m, W2=4.6≈í¬∫m, W3=12≈í¬∫m</ShortDescription>
                    <ErrorDescription>Please select at least one band.</ErrorDescription>
                    <EnumValue id="1">
                        <Title>W1</Title>
                    </EnumValue>
                    <EnumValue id="2">
                        <Title>W2</Title>
                    </EnumValue>
                    <EnumValue id="3">
                        <Title>W3</Title>
                    </EnumValue>
                </EnumString>
            </FieldGroup>
            <xi:include href="wise/wise_1b_optional.xml"/>
        </Form>
    </ImageSet>

    <ImageSet name="wise_cryo_3band_3a">
        <Title>3-Band Cryo Atlas</Title>
        <Desc>Search WISE 3-Band Cryo Atlas</Desc>
        <DataSource searchProcId="ibe_processor">
            <Param key="mission" value="wise"/>
            <Param key="ImageSet" value="cryo_3band"/>
            <Param key="ProductLevel" value="3a"/>
        </DataSource>

        <Form>
            <FieldGroup align="left">
                <EnumString>
                    <Name>band</Name>
                    <Title>Return the following bands:</Title>
                    <PreferWidth>150</PreferWidth>
                    <Default>_all_</Default>
                    <Mask>[CHECKBOX]</Mask>
                    <ShortDescription>Band Selection: W1=3.4≈í¬∫m, W2=4.6≈í¬∫m, W3=12≈í¬∫m</ShortDescription>
                    <ErrorDescription>Please select at least one band.</ErrorDescription>
                    <EnumValue id="1">
                        <Title>W1</Title>
                    </EnumValue>
                    <EnumValue id="2">
                        <Title>W2</Title>
                    </EnumValue>
                    <EnumValue id="3">
                        <Title>W3</Title>
                    </EnumValue>
                </EnumString>
            </FieldGroup>
            <xi:include href="wise/wise_3a_optional.xml"/>
        </Form>
    </ImageSet>

    <ImageSet name="wise_postryo_1b">
        <Title>Post-Cryo (2 band) Single Exposure</Title>
        <Desc>Search WISE Post-Cryo (2 band) Single Exposure</Desc>
        <DataSource searchProcId="ibe_processor">
            <Param key="mission" value="wise"/>
            <Param key="ImageSet" value="postcryo"/>
            <Param key="ProductLevel" value="1b"/>
        </DataSource>

        <Form>
            &few_frameop_visi_cntrl;
            <FieldGroup align="left">
                <EnumString>
                    <Name>band</Name>
                    <Title>Return the following bands:</Title>
                    <PreferWidth>150</PreferWidth>
                    <Default>_all_</Default>
                    <Mask>[CHECKBOX]</Mask>
                    <ShortDescription>Band Selection: W1=3.4≈í¬∫m, W2=4.6≈í¬∫m</ShortDescription>
                    <ErrorDescription>Please select at least one band.</ErrorDescription>
                    <EnumValue id="1">
                        <Title>W1</Title>
                    </EnumValue>
                    <EnumValue id="2">
                        <Title>W2</Title>
                    </EnumValue>
                </EnumString>
            </FieldGroup>
            <xi:include href="wise/wise_1b_optional.xml"/>
        </Form>
    </ImageSet>

</Mission>

=== Caltech-IPAC/firefly/config/fuse/configurable/wise/wise_3a_optional.xml
<!DOCTYPE FieldGroup SYSTEM "../Mission.dtd">

<FieldGroup type="activeCollapsiblePanel" typeName="L3" labelWidth="200">
    <Title>Optional constraints for Atlas (Level 3) data</Title>
    <FieldGroup labelWidth="144">
        <String>
            <Name>coaddId</Name>
            <Title>Coadd ID(s)</Title>
            <PreferWidth>50</PreferWidth>
            <NullAllowed/>
            <ShortDescription>Optionally provide one or more Coadd ID(s) separated by space or comma: 2029p469_ab41, 0016p257_ab41</ShortDescription>
        </String>
    </FieldGroup>
</FieldGroup>

=== Caltech-IPAC/firefly/config/fuse/configurable/2mass/2mass_optional.xml
<!DOCTYPE Form SYSTEM "../Mission.dtd">

<Form>
    <FieldGroup align="left">
        <EnumString>
            <Name>band</Name>
            <Title>Return the following bands:</Title>
            <PreferWidth>150</PreferWidth>
            <Default>A</Default>
            <Mask>[CHECKBOX]</Mask>
            <NullAllowed/>
            <ShortDescription>Limits 2MASS images returned to those with the given 2MASS Band.</ShortDescription>
            <ErrorDescription>Please select at least one band.</ErrorDescription>
            <EnumValue id="A">
                <Title>All 2MASS Bands</Title>
            </EnumValue>
            <EnumValue id="J">
                <Title>2MASS J-Band</Title>
            </EnumValue>
            <EnumValue id="H">
                <Title>2MASS H-Band</Title>
            </EnumValue>
            <EnumValue id="K">
                <Title>2MASS Ks-Band</Title>
            </EnumValue>
        </EnumString>
    </FieldGroup>
    <FieldGroup type="activeCollapsiblePanel" typeName="2massConstr" labelWidth="200">
        <Title>Optional constraints for 2MASS image search</Title>
        <FieldGroup labelWidth="580">
            <FieldGroup direction="horizontal" labelWidth="130">
                <Date>
                    <Name>xdate</Name>
                    <Title>Reference Date</Title>
                    <NullAllowed/>
                    <ShortDescription>Reference date, specified in yyyy-MM-dd format. (Can differ by one day from the actual UT observation time.)</ShortDescription>
                    <ErrorDescription>Format error!</ErrorDescription>
                    <Format>yyyy-MM-dd</Format>
                </Date>
            </FieldGroup>
            <Label>
                <![CDATA[<i>&nbsp;&nbsp;&nbsp;&nbsp;Enter reference date, format example: </i>1998-03-04<i>.</i><br><br>]]></Label>
        </FieldGroup>
        <FieldGroup align="left">
            <EnumString orientation="horizontal">
                <Name>hem</Name>
                <Title>Hemisphere:</Title>
                <PreferWidth>150</PreferWidth>
                <Default>n</Default>
                <Mask>[RADIO]</Mask>
                <NullAllowed/>
                <ShortDescription>The hemisphere of the 2MASS observatory where the FITS images to return were taken.</ShortDescription>
                <ErrorDescription>Select one.</ErrorDescription>
                <EnumValue id="n">
                    <Title>north (Mt. Hopkins)</Title>
                </EnumValue>
                <EnumValue id="s">
                    <Title>south (Cerro Tololo)</Title>
                </EnumValue>
            </EnumString>
        </FieldGroup>
        <FieldGroup align="left" labelWidth="144">
            <String>
                <Name>scan</Name>
                <Title>Scan Number</Title>
                <PreferWidth>50</PreferWidth>
                <NullAllowed/>
                <ShortDescription>Optionally provide the nightly scan number (a positive integer) of the FITS images to return, example: 13.</ShortDescription>
            </String>
        </FieldGroup>
    </FieldGroup>

</Form>

=== Caltech-IPAC/firefly/config/fuse/configurable/wise/wise_1b_optional.xml
<!DOCTYPE FieldGroup SYSTEM "../Mission.dtd">

<FieldGroup type="activeCollapsiblePanel" typeName="L1" labelWidth="200">
    <Title>Optional constraints for Single Exposure (Level 1b) data</Title>
    <FieldGroup labelWidth="580">
        <FieldGroup direction="horizontal" labelWidth="130">
            <Date>
                <Name>timeStart</Name>
                <Title>Start Date (UT)</Title>
                <NullAllowed/>
                <ShortDescription>Period start (yyyy-MM-dd [HH:mm:ss])</ShortDescription>
                <ErrorDescription>Format error!</ErrorDescription>
                <Format>yyyy-MM-dd;yyyy-MM-dd HH:mm:ss</Format>
            </Date>
            <Date>
                <Name>timeEnd</Name>
                <Title>End Date (UT)</Title>
                <NullAllowed/>
                <ShortDescription>Period end (yyyy-MM-dd [HH:mm:ss])</ShortDescription>
                <ErrorDescription>Format error!</ErrorDescription>
                <Format>yyyy-MM-dd;yyyy-MM-dd HH:mm:ss</Format>
            </Date>
        </FieldGroup>
        <Label>
            <![CDATA[<i>&nbsp;&nbsp;&nbsp;&nbsp;Enter date range to search, format example: </i>2010-01-10 15:30:00<i>, or </i>2010-01-10<i>.</i><br><br>]]></Label>
    </FieldGroup>
    <FieldGroup align="left" labelWidth="144">
        <String>
            <Name>scanId</Name>
            <Title>Scan ID(s)</Title>
            <PreferWidth>50</PreferWidth>
            <NullAllowed/>
            <ShortDescription>Optionally provide one of more WISE scan identifier(s) separated by space or comma: 00712a, 01432a, 05693b.  Together with an in-scan frame number, scan ID uniquely identifies a single epoch WISE image set .</ShortDescription>
        </String>
        <FieldGroup direction="horizontal" labelWidth="144">
            <EnumString orientation="vertical">
                <Name>frameOp</Name>
                <Title>Frame Number(s) (optional)</Title>
                <Default>eq</Default>
                <NullAllowed/>
                <ShortDescription>A WISE L1b image frame number or an acceptable frame number range may be provided.

In multi-input mode, these constraints apply only if the input table does not have a frame_min or frame_max column.

Frame numbers are non-negative integers uniquely identifying an image set within a specific scan.</ShortDescription>
                <EnumValue id="eq">
                    <Title>=</Title>
                </EnumValue>
                <EnumValue id="gt">
                    <Title>&gt;</Title>
                </EnumValue>
                <EnumValue id="lt">
                    <Title>&lt;</Title>
                </EnumValue>
                <EnumValue id="in">
                    <Title>IN</Title>
                </EnumValue>
                <EnumValue id="be">
                    <Title>BETWEEN</Title>
                </EnumValue>
            </EnumString>
            <FieldGroup align="left" direction="horizontal" labelWidth="1">
                <Label><![CDATA[<div style='width:18px'>&nbsp;</div]]></Label>
                <String>
                    <Name>frameVal1</Name>
                    <Title></Title>
                    <PreferWidth>10</PreferWidth>
                    <NullAllowed/>
                    <ShortDescription>Enter frame number</ShortDescription>
                </String>
                <String>
                    <Name>frameVal2</Name>
                    <Title></Title>
                    <PreferWidth>10</PreferWidth>
                    <NullAllowed/>
                    <ShortDescription>Enter end frame number</ShortDescription>
                </String>
                <String>
                    <Name>frameVal3</Name>
                    <Title></Title>
                    <PreferWidth>30</PreferWidth>
                    <NullAllowed/>
                    <ShortDescription>Enter list of frame numbers</ShortDescription>
                </String>
            </FieldGroup>
        </FieldGroup>
    </FieldGroup>
</FieldGroup>
