=== Caltech-IPAC/firefly/config/fuse/configurable/Dataset.dtd
<!ELEMENT  Dataset (Title, SpacialTypes?, Desc?, CatalogSet*, ImageSet*, Spectrum*)>
        <!ATTLIST    Dataset name CDATA #REQUIRED>
        <!ATTLIST    Dataset dataTypes CDATA #IMPLIED>      <!-- comma separated types.. imageset,catalog,spectrum -->

        <!-- comma separated values -->
        <!--Cone|Elliptical|Box|Polygon|MultiTableUpload|MultiPrevSearch|MultiPoints|AllSky-->
        <!ELEMENT  SpacialTypes EMPTY>
        <!ATTLIST    SpacialTypes catalog CDATA #IMPLIED>
        <!ATTLIST    SpacialTypes spectrum CDATA #IMPLIED>
        <!ATTLIST    SpacialTypes imageSet CDATA #IMPLIED>

        <!ENTITY % dataSetElements
                "Title, Desc?, DataSource?, Form?, Download?"
                >

        <!ELEMENT  ImageSet (%dataSetElements;)>
        <!ATTLIST    ImageSet name CDATA #REQUIRED>

        <!ELEMENT  CatalogSet (%dataSetElements;)>
        <!ATTLIST    CatalogSet name CDATA #REQUIRED>

        <!ELEMENT  Spectrum (%dataSetElements;)>
        <!ATTLIST    Spectrum name CDATA #REQUIRED>

        <!ELEMENT  DataSource (IBE?, TAP?, Param*)>
        <!ATTLIST    DataSource searchProcId CDATA #REQUIRED>

        <!ELEMENT  IBE EMPTY>
        <!ATTLIST    IBE baseUrl CDATA #IMPLIED>
        <!ATTLIST    IBE action     (search|data|docs) "search">
        <!ATTLIST    IBE mission    CDATA #IMPLIED>
        <!ATTLIST    IBE dataSet    CDATA #IMPLIED>
        <!ATTLIST    IBE tableName  CDATA #IMPLIED>

        <!ELEMENT  TAP EMPTY>
        <!ATTLIST    TAP baseUrl    CDATA #IMPLIED>
        <!ATTLIST    TAP queryStr   CDATA #IMPLIED>

        <!-- Used for passing key-value pair data to the server. -->
        <!ELEMENT  Param EMPTY>
        <!-- A key mapping to a single value, duplicate keys are not allowed. -->
        <!ATTLIST    Param key CDATA #REQUIRED>
        <!ATTLIST    Param value CDATA #REQUIRED>

        <!ELEMENT  Form (FieldGroup+)>
        <!ATTLIST    Form title CDATA #IMPLIED>
        <!ATTLIST    Form minSize CDATA #IMPLIED>
        <!ATTLIST    Form helpId CDATA #IMPLIED>

        <!-- This popup panel provides an interface for downloading catalog and image files. -->
        <!ELEMENT  Download (Form?, Param*)>
        <!ATTLIST    Download id CDATA #REQUIRED>
        <!ATTLIST    Download title CDATA #IMPLIED>
        <!ATTLIST    Download filePrefix CDATA #IMPLIED>
        <!ATTLIST    Download titlePrefix CDATA #IMPLIED>
        <!ATTLIST    Download maxRows CDATA #IMPLIED>

        <!-- This panel provides ... -->
        <!ELEMENT  FieldGroup (Title?, Tooltip?, Access?, (FieldGroup|PreDefField|Label|HIDDEN|String|Date|DEGREE|Double|Float|EMail|EnumString|Integer|Password|Pattern|Lat|Lon|MultiCoord|File|Help)*)>
        <!ATTLIST    FieldGroup xid CDATA #IMPLIED>
        <!ATTLIST    FieldGroup ref-xid CDATA #IMPLIED>
        <!-- A string defining the FieldGroup's panel type. -->
        <!ATTLIST    FieldGroup type (default|tabPane|activeTabPane|collapsiblePanel|activeCollapsiblePanel|datePanel|frame) "default">
        <!ATTLIST    FieldGroup typeName CDATA #IMPLIED>
        <!ATTLIST    FieldGroup labelWidth CDATA "100">
        <!ATTLIST    FieldGroup direction (vertical|horizontal) "vertical">
        <!ATTLIST    FieldGroup width CDATA #IMPLIED>
        <!ATTLIST    FieldGroup height CDATA #IMPLIED>
        <!ATTLIST    FieldGroup spacing CDATA "0">
        <!ATTLIST    FieldGroup align (left|center|right) "right">
        <!ATTLIST    FieldGroup downloadRestriction CDATA #IMPLIED>

        <!-- This element defines the pre-defined fields for inputing parameters. -->
        <!ELEMENT  PreDefField (Param*)>
        <!-- A string that identitfies one of the available pre-defined inputs. Possible preDefField values are: "targetPanel", "RangePanel", "catalogPopupPanel", ... -->
        <!ATTLIST    PreDefField id CDATA #REQUIRED>

        <!ELEMENT  Access EMPTY>
        <!-- A comma delimited string of roles. The included roles will allow access to the content. -->
        <!ATTLIST    Access includes CDATA #IMPLIED>
        <!-- A comma delimited string of roles. The included roles will exclude access to the content. -->
        <!ATTLIST    Access excludes CDATA #IMPLIED>


        <!ENTITY % fieldElements
                "ID?, Name, Title, PreferWidth?, Icon?, Default?, Pref-Key?, Mask?, MaxWidth?, NullAllowed?, LongDescription?, ShortDescription?, ErrorDescription?"
                >
        <!ENTITY % boundTypes
                "(exclusive|inclusive|undefined) 'undefined'"
                >

        <!ELEMENT  HIDDEN (ID?, Name, Default)>
        <!ELEMENT  String (%fieldElements;)>
        <!ELEMENT  Date (%fieldElements;, Min?, Max?, Format*)>
        <!ATTLIST    Date minBoundType %boundTypes;>
        <!ATTLIST    Date maxBoundType %boundTypes;>
        <!ELEMENT  DEGREE (%fieldElements;, Min?, Max?)>
        <!ATTLIST    DEGREE units (degree|arcmin|arcsec) "degree">
        <!ELEMENT  Double (%fieldElements;, Min?, Max?, Precision?)>
        <!ATTLIST    Double scientificAllowed (true|false) "false">
        <!ATTLIST    Double minBoundType %boundTypes;>
        <!ATTLIST    Double maxBoundType %boundTypes;>
        <!ELEMENT  Float (Min?, Max?, Precision?)>
        <!ATTLIST    Float scientificAllowed (true|false) "false">
        <!ATTLIST    Float minBoundType %boundTypes;>
        <!ATTLIST    Float maxBoundType %boundTypes;>
        <!ELEMENT  EMail (%fieldElements;)>
        <!ELEMENT  EnumString (%fieldElements;, EnumValue+)>
        <!ATTLIST    EnumString orientation (horizontal|vertical) "horizontal">
        <!ELEMENT  Integer (%fieldElements;)>
        <!ELEMENT  Lat (%fieldElements;)>
        <!ELEMENT  Lon (%fieldElements;)>
        <!ELEMENT  MultiCoord (%fieldElements;)>
        <!ELEMENT  Password (%fieldElements;)>
        <!ELEMENT  Pattern (%fieldElements;)>
        <!ELEMENT  File (%fieldElements;)>
        <!ELEMENT  Help (Title)>
        <!ATTLIST    Help helpId CDATA #REQUIRED>
        <!ELEMENT  EnumValue (Title, ShortDescription?, IntValue?)>
        <!ATTLIST    EnumValue id CDATA #REQUIRED>


        <!ELEMENT  NullAllowed EMPTY>

        <!ELEMENT  Label (#PCDATA)>
        <!ELEMENT  ID (#PCDATA)>
        <!ELEMENT  Name (#PCDATA)>
        <!ELEMENT  Title (#PCDATA)>
        <!ELEMENT  title (#PCDATA)>
        <!ATTLIST  Title  width CDATA #IMPLIED>
        <!ELEMENT  Tooltip (#PCDATA)>
        <!ELEMENT  Desc (#PCDATA)>
        <!ELEMENT  desc (#PCDATA)>
        <!ELEMENT  LongDescription (#PCDATA)>
        <!ELEMENT  ShortDescription (#PCDATA)>
        <!ELEMENT  Icon (#PCDATA)>
        <!ELEMENT  Default (#PCDATA)>
        <!ELEMENT  Pref-Key (#PCDATA)>
        <!ELEMENT  ErrorDescription (#PCDATA)>
        <!ELEMENT  Mask (#PCDATA)>
        <!ELEMENT  ValidateMask (#PCDATA)>
        <!ELEMENT  PreferWidth (#PCDATA)>
        <!ELEMENT  Size (#PCDATA)>
        <!ELEMENT  MaxWidth (#PCDATA)>
        <!ELEMENT  Value (#PCDATA)>
        <!ELEMENT  IntValue (#PCDATA)>
        <!ELEMENT  Format (#PCDATA)>
        <!ELEMENT  Min (#PCDATA)>
        <!ELEMENT  Max (#PCDATA)>
        <!ELEMENT  Precision (#PCDATA)>


        <!ELEMENT xi:include EMPTY>
        <!ATTLIST xi:include
                xmlns:xi   CDATA       #FIXED    "http://www.w3.org/2001/XInclude"
                href       CDATA       #REQUIRED
                parse      (xml|text)  "xml"
                >

=== Caltech-IPAC/firefly/config/fuse/configurable/planck.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Dataset SYSTEM "dataset.dtd">

<Dataset name="planck" dataTypes="ImageSet,Catalog">
    <Title>Planck</Title>
    <SpacialTypes catalog="Cone,Box,Polygon" imageSet="Cone,Box,Polygon"/>
    <Desc>This is a test dataset</Desc>
    <CatalogSet name="planck_band2_cat">
        <Title>Planck Band 2 Catalog</Title>
        <Desc>Planck Band 2 Catalog descriptions</Desc>
        <DataSource searchProcId="tap_processor">
            <TAP baseUrl="http://localhost:8080" queryStr="SELECT * FROM magnitudes as m where m.r=10 and m.r=16"/>
            <Param key="specialPlanckParam" value="only for planck"/>
        </DataSource>
    </CatalogSet>
    <ImageSet name="planck_band2">
        <Title>Planck Band 2</Title>
        <Desc>Planck Band 2 descriptions</Desc>
        <DataSource searchProcId="ibe_processor">
            <IBE baseUrl="http://localhost:8080" dataSet="planckb2" mission="planck" tableName="tbl_planck_b2"/>
            <Param key="specialPlanckParam" value="only for planck"/>
        </DataSource>
        <Form>
            <!-- Planck TOI search parameters-->
            <FieldGroup align="left">
                <!--
                <DEGREE units="degree">
                    <Name>sradius</Name>
                    <Title>Search Size</Title>
                    <Default>1.0</Default>
                    <ShortDescription>Specifies the size of the desired search size.</ShortDescription>
                    <ErrorDescription>Invalid entry!</ErrorDescription>
                    <Min>0.1666666</Min>
                    <Max>2</Max>
                </DEGREE>
                -->
                <EnumString orientation="vertical">
                    <Name>planckfreq</Name>
                    <Title>Select Frequency</Title>
                    <PreferWidth>225</PreferWidth>
                    <Default>100</Default>
                    <ErrorDescription>Please select at least one catalogs</ErrorDescription>
                    <EnumValue id="_all_">
                        <Title>All</Title>
                    </EnumValue>
                    <EnumValue id="30">
                        <Title>30 GHz</Title>
                    </EnumValue>
                    <EnumValue id="44">
                        <Title>44 GHz</Title>
                    </EnumValue>
                    <EnumValue id="70">
                        <Title>70 GHz</Title>
                    </EnumValue>
                    <EnumValue id="100">
                        <Title>100 GHz</Title>
                    </EnumValue>
                    <EnumValue id="143">
                        <Title>143 GHz</Title>
                    </EnumValue>
                    <EnumValue id="217">
                        <Title>217 GHz</Title>
                    </EnumValue>
                    <EnumValue id="353">
                        <Title>353 GHz</Title>
                    </EnumValue>
                    <EnumValue id="545">
                        <Title>545 GHz</Title>
                    </EnumValue>
                    <EnumValue id="857">
                        <Title>857 GHz</Title>
                    </EnumValue>
                </EnumString>
                <EnumString orientation="horizontal">
                    <Name>detc100</Name>
                    <Title>Select Detector(s)</Title>
                    <PreferWidth>225</PreferWidth>
                    <!--<Mask>[CHECKBOX]</Mask>-->
                    <Default>1a</Default>
                    <ErrorDescription>Please select at least one catalogs</ErrorDescription>
                    <EnumValue id="_all_">
                        <Title>All</Title>
                    </EnumValue>
                    <EnumValue id="1a">
                        <Title>1a</Title>
                    </EnumValue>
                    <EnumValue id="1b">
                        <Title>1b</Title>
                    </EnumValue>
                    <EnumValue id="2a">
                        <Title>2a</Title>
                    </EnumValue>
                    <EnumValue id="2b">
                        <Title>2b</Title>
                    </EnumValue>
                    <EnumValue id="3a">
                        <Title>3a</Title>
                    </EnumValue>
                    <EnumValue id="3b">
                        <Title>3b</Title>
                    </EnumValue>
                    <EnumValue id="4a">
                        <Title>4a</Title>
                    </EnumValue>
                    <EnumValue id="4b">
                        <Title>4b</Title>
                    </EnumValue>
                </EnumString>
            </FieldGroup>
        </Form>
    </ImageSet>

</Dataset>
